CBIIT/crdc-datahub-ui

src/components/Contexts/FormContext.test.tsx
src/components/ProgressBar/ProgressBar.tsx
src/content/questionnaire/FormView.tsx
src/content/questionnaire/ListingView.tsx
src/layouts/index.tsx
src/types/Application.d.ts

This resolves an issue with the Application type in which the key `id` is used instead of the GQL defined `_id`.

Fix incorrect Application type

---

src/components/Header/HeaderMobile.tsx
src/components/Header/HeaderTablet.tsx
src/components/Header/components/NavbarDesktop.tsx
src/components/Questionnaire/FormContainer.tsx
src/components/ScrollButton/ScrollButtonView.tsx
src/components/StatusBar/StatusBar.tsx
src/content/questionnaire/FormView.tsx
src/layouts/index.tsx

Just some additional minor updates to fix some issues with latest merge.
- Added back Nunito fonts
- Fixed mapping missing keys and causing error message
- Fixed click scroll to top without requiring a refresh (The form was not happy)
- Fixed spacing around form and header navigation overflow issue
- Fixed login placement and styling

Minor updates

---

conf/inject.template.js
src/content/questionnaire/sections/B.tsx
src/layouts/index.tsx
tsconfig.json

The changes in this PR. 
1. Small updates on ESlint issues found on dev branch 
2. Enlarge the minHeight to avoid the empty space below the footer.  Temporary.

Small updates on ESlint issues found on dev branch

---

src/components/Header/HeaderMobile.tsx
src/components/Header/HeaderTablet.tsx
src/components/Header/components/LogoDesktop.tsx
src/components/Header/components/LogoMobile.tsx
src/components/Header/components/LogoTablet.tsx
src/components/Header/components/NavbarDesktop.tsx
src/components/Header/components/SearchBarDesktop.tsx
src/components/Header/components/SearchBarMobile.tsx
src/components/Header/components/SearchBarTablet.tsx
src/components/ProgressBar/ProgressBar.tsx
src/components/Questionnaire/AdditionalContact.tsx
src/components/Questionnaire/DatePickerInput.tsx
src/components/Questionnaire/FormGroupCheckbox.tsx
src/components/Questionnaire/PlannedPublication.tsx
src/components/Questionnaire/Publication.tsx
src/components/Questionnaire/TableAutocompleteInput.tsx
src/components/Questionnaire/TimeConstraint.tsx
src/components/StatusBar/components/HistorySection.tsx
src/components/StatusBar/components/StatusSection.tsx
src/config/SectionConfig.ts
src/config/globalHeaderData.tsx
src/content/questionnaire/sections/A.tsx
src/content/questionnaire/sections/B.tsx
src/content/questionnaire/sections/C.tsx
src/content/questionnaire/sections/D.tsx
src/types/Globals.d.ts

For QA reasons, we need IDs on interactable components (inputs and buttons). I added ID's to these components in the header and the questionnaire content.

Adding ids to interactable items in header and form

---

.env.example
src/content/login/Controller.tsx

Jira ticket [CRDCDH-39](https://tracker.nci.nih.gov/browse/CRDCDH-39)

CRDCDH-39 Part 2

---

src/components/Contexts/FormContext.tsx
src/components/StatusBar/components/HistorySection.tsx
src/components/StatusBar/components/StatusSection.tsx
src/components/StatusBar/utils.ts
src/content/questionnaire/sections/A.tsx
src/utils/dateUtils.ts
src/utils/index.ts

**Overview**
This PR is to fix the "Unsaved Changes" dialog from appearing when switching between form sections even when there hasn't been any new changes made.

Form detecting false positive changes

---

src/content/login/Controller.tsx

https://tracker.nci.nih.gov/browse/CRDCDH-39

CRDCDH-39 Part 3

---

src/components/Questionnaire/AdditionalContact.tsx
src/config/InitialValues.ts
src/content/questionnaire/FormView.tsx
src/content/questionnaire/sections/A.tsx
src/types/Application.d.ts

This PR updates Section A placeholders and the Questionnaire (Submission) form page title per [CRDCDH-131](https://tracker.nci.nih.gov/browse/CRDCDH-131)

CRDCDH-131 Remove eRAA field and update placeholders

---

src/components/Questionnaire/Repository.tsx
src/content/questionnaire/FormView.tsx
src/content/questionnaire/sections/B.tsx

Adding missing ID's to section b and formView navigation buttons.

adding ids to section b and formview

---

src/components/Questionnaire/TableFileTypeAndExtensionInput.tsx
src/config/FileTypeConfig.ts
src/content/questionnaire/sections/D.tsx

As Kailing suggested, deleting other types from the file type and extension inputs, replacing with Enter or select.

deleting file other types

---

src/components/Questionnaire/SectionGroup.tsx
src/content/questionnaire/sections/A.tsx
src/content/questionnaire/sections/B.tsx
src/content/questionnaire/sections/C.tsx
src/content/questionnaire/sections/D.tsx

This PR updates the base input section grouping component to match the newest UI styling and modifies the titles/descriptions for section A per ticket [CRDCDH-168](https://tracker.nci.nih.gov/browse/CRDCDH-168)

CRDCDH-168 Update Section A section groups

---

public/index.html
public/injectEnv.js
src/components/Header/components/NavbarDesktop.tsx

Update the index.html to replace the native react content in meta
Include the user profile within  user dropdown menu

Refinements

---

src/components/SystemUseWarningOverlay/OverlayText.tsx
src/components/SystemUseWarningOverlay/OverlayWindow.tsx
src/layouts/index.tsx

This implements ticket 144 which is the warning banner on first load. It's a copy paste from bento's implementation also converting their MUI v4 to our MUI v5.

adding warning overlay

---

src/components/ScrollButton/ScrollButtonStyles.css

This just fixes a small scroll to top issue with style transition

fix scroll to top styles

---

src/components/Contexts/FormContext.tsx
src/content/questionnaire/ListView.tsx
src/graphql/listApplications.ts

- **This PR primarily updates the ListView to create an empty application before redirect**. 
- Adds the new column `Last Updated Date` based off of the `updatedAt` field to the Submission Request List table per new requirements.
- This also will fix an issue with MVP-2 showing incorrect buttons to Org Owners.

CRDCDH-54 Misc changes to Listview

---

src/content/questionnaire/ListView.tsx

Changes were approved but merged into the wrong target.

Merge Approved CRDCDH-54 Updates

---

src/components/Questionnaire/RadioYesNoInput.tsx
src/content/questionnaire/sections/D.tsx

This fixes a bug in section D, where the form would not be marked complete because of a incorrectly setting validation on an invisible component.
Now the section D form should save properly, even when the imagingDeIdentified component is invisbile.

Crdcdh 45 validation bugfix

---

package.json
src/components/ProgressBar/ProgressBar.tsx
src/components/ProgressBar/StatusAdornment.tsx
src/components/StatusBar/StatusBar.test.tsx
src/components/StatusBar/StatusBar.tsx
src/config/SectionConfig.ts
src/content/questionnaire/ListView.tsx
src/types/Application.d.ts
src/types/Auth.d.ts
src/utils/dateUtils.ts

This PR covers:
- Adds UTC support and conversion to local time
- Updates CRDCDH-54 ListView to fix pagination offset issue
- Updates Section A and Review section titles per CRDCDH-38 newest changes
- Removes the direct usage of emotion CSS from related components

Add UTC support & minor ListView bug fix

---

src/config/globalFooterData.tsx

implements ticket 202. changing footer links.

changing footer links

---

src/components/Questionnaire/AutocompleteInput.tsx
src/components/Questionnaire/FundingAgency.tsx
src/components/Questionnaire/PlannedPublication.tsx
src/components/Questionnaire/Publication.tsx
src/components/Questionnaire/Repository.tsx
src/components/Questionnaire/SelectInput.tsx
src/config/DataTypesConfig.ts
src/config/FundingConfig.ts
src/config/InitialValues.ts
src/config/ProgramConfig.ts
src/config/SectionConfig.ts
src/content/questionnaire/sections/B.tsx
src/content/questionnaire/sections/Review.tsx
src/types/Application.d.ts
src/types/ProgramConfig.d.ts
src/utils/formUtils.test.ts
src/utils/formUtils.ts
src/utils/stringUtils.test.ts
src/utils/stringUtils.ts

**OVERVIEW**
This PR aims to update the content and logic of section B to better reflect the new changes. 
- Program and Study no longer have connected logic. Added notApplicable property to add a "Not Applicable" option in program dropdown. 
- Moved Funding Agency to separate component and added ability to add multiple, but at least one is always required
- Update formUtils to reflect new Program/Study logic as well as new tests
- Updated static data from dropdowns
**TICKETS**
[CRDCDH-35](https://tracker.nci.nih.gov/browse/CRDCDH-35)

CRDCDH-35 Section B Updates

---

src/content/questionnaire/sections/C.tsx
src/utils/stringUtils.test.ts
src/utils/stringUtils.ts

**OVERVIEW**
This PR aims to prevent the user from typing anything other than integers into the field. I also converted the input to a text field to avoid unwanted default browser behavior.
**TICKETS**
[CRDCDH-36](https://tracker.nci.nih.gov/browse/CRDCDH-36)

CRDCDH-36 Small Integer Validation Update

---

.fork-ts-checkerrc
package.json
src/utils/formUtils.test.ts

This PR fixes extra line gaps that caused a build failure. It also adds a config file for ForkTS which resolves a out-of-memory error occasionally when switching branches.

Fix build errors

---

src/config/ProgramConfig.ts
src/content/questionnaire/sections/B.tsx
src/content/questionnaire/sections/Review.tsx
src/types/ProgramConfig.d.ts

**OVERVIEW**
This PR aims to add a description for pre-defined program options (CCDI and HTAN), as well as making the pre-populate the program description field.
**TICKETS**
[CRDCDH-205](https://tracker.nci.nih.gov/browse/CRDCDH-205)

CRDCDH-205 Adding Pre-defined Program Descriptions

---

src/layouts/index.tsx

Addresses Ticket 242. Small typo for the page title.

page title typo fix

---

src/components/Questionnaire/Repository.tsx
src/components/Questionnaire/ReviewDataListing.tsx
src/components/Questionnaire/ReviewDataListingProperty.tsx
src/components/Questionnaire/ReviewFileTypeTable.tsx
src/components/Questionnaire/ReviewSection.tsx
src/components/Questionnaire/SectionGroup.tsx
src/components/Questionnaire/SelectInput.tsx
src/config/SectionConfig.tsx
src/config/SectionMetadata.tsx
src/content/questionnaire/FormView.tsx
src/content/questionnaire/sections/A.tsx
src/content/questionnaire/sections/B.tsx
src/content/questionnaire/sections/C.tsx
src/content/questionnaire/sections/D.tsx
src/content/questionnaire/sections/Review.tsx

**OVERVIEW**
This PR aims to update the Review section page to reflect the new changes made in sections A-D as well as some styling changes.
- Updated Review page to include all section titles/descriptions and styling. Made a shared sectionMetadata file to ensure text is the same in both places
- Updated Sections A-D to use the new sectionMetadata for titles/descriptions
- Adjusted sidebar spacing so that it touches the top of the screen
- Fixed SelectInput edge case causing page to crash when invalid data (old form data) is passed to it and select allows multiple
**TICKETS**
[CRDCDH-47](https://tracker.nci.nih.gov/browse/CRDCDH-47)

CRDCDH-47 Review Page Updates

---

src/config/ProgramConfig.ts

**OVERVIEW**
This PR aims to add CPTAC and DCCPS to the existing program options.
**TICKETS**
[CRDCDH-266](https://tracker.nci.nih.gov/browse/CRDCDH-266)

CRDCDH-266

---

src/components/InactivityDialog/InactivityDialog.tsx

I accidentally left some testing code which unpacked the data from the endpoint incorrectly.
I fixed this bug here.

Crdcdh 65 bugfix

---

src/content/questionnaire/sections/D.tsx

This fixes the bugs listed in tickets 296 and 297. Adding character limits to text inputs.

adding max char limits bugfix

---

src/content/questionnaire/sections/B.tsx

**OVERVIEW**
This PR updated dbGap label in section B
**TICKETS**
[CRDCDH-318](https://tracker.nci.nih.gov/browse/CRDCDH-318)

CRDCDH-318

---

src/components/Contexts/FormContext.tsx
src/components/Questionnaire/DatePickerInput.tsx
src/content/questionnaire/sections/B.tsx
src/content/questionnaire/sections/D.tsx

**OVERVIEW**
This PR aims to add additional error validation messages for past dates, invalid date, required/empty date. Additionally, I fixed some additional existing date picker bugs
- Fixed DatePickerInput to allow for empty field when not required
- Fixed DatePickerInput to not fail validation when field is equal to the format pattern (MM/DD/YYYY) and field not required
- Fixed DatePickerInput to catch validation errors when backspacing on input
- Updated sections B and D to default to format pattern when date is invalid to prevent unsaved changes dialog from popping up 
**TICKETS**
[CRDCDH-308](https://tracker.nci.nih.gov/browse/CRDCDH-308)

CRDCDH-308 Date Updates

---

src/config/globalHeaderData.tsx

The Data Submission feature is implemented in MVP2-M2, remove the Data Submission menu from the nav bar in MVP-1.

removing data submissions from navbar for mvp-1

---

src/components/Header/HeaderTabletAndMobile.tsx
src/components/Header/components/NavbarDesktop.tsx
src/config/AuthRoles.ts
src/content/questionnaire/ListView.tsx
src/content/users/Controller.tsx
src/content/users/ListView.tsx
src/types/Auth.d.ts
src/utils/formModeUtils.test.ts
src/utils/formModeUtils.ts
src/utils/profileUtils.test.ts

Reverts CBIIT/crdc-datahub-ui#118

Revert "CRDCDH-359 Update user roles to match BE"

---

src/components/Header/HeaderTabletAndMobile.tsx
src/components/Header/components/NavbarDesktop.tsx
src/config/AuthRoles.ts
src/content/questionnaire/ListView.tsx
src/content/users/Controller.tsx
src/content/users/ListView.tsx
src/types/Auth.d.ts
src/utils/formModeUtils.test.ts
src/utils/formModeUtils.ts
src/utils/profileUtils.test.ts

Reverts CBIIT/crdc-datahub-ui#119. On hold for BE.

Revert the Revert... "CRDCDH-359 Update user roles to match BE"

---

src/components/Questionnaire/DatePickerInput.tsx

**OVERVIEW**
This PR aims to make a small adjustment to the DatePickerInput changes previously made. 
- Fixed invalid format error not showing up when field is required
- Fixed invalid format error not always being detected
**TICKETS**
[CRDCDH-308](https://tracker.nci.nih.gov/browse/CRDCDH-308)

CRDCDH-308-Date-Edgecase-Fix

---

src/components/Questionnaire/SectionGroup.tsx
src/config/SectionMetadata.tsx
src/content/questionnaire/sections/D.tsx

This implements ticket 366, which requires at least one data type to be selected as yes, or that "Other data types" has characters in it, in section D.

require at least one data type

---

src/components/Footer/FooterDesktop.tsx
src/components/Footer/FooterMobile.tsx
src/components/Footer/FooterTablet.tsx

This addresses text wrapping in the footer

stop wrapping in footer

---

src/components/Contexts/FormContext.tsx
src/components/GenericAlert/index.tsx
src/components/ProgressBar/ProgressBar.tsx
src/config/ErrorCodes.ts
src/content/questionnaire/FormView.tsx

**OVERVIEW**
This PR aims to check if a unique Study Abbreviation is being used during a Submission Request.
- Catch errors while saving
- If error due to Study Abbreviation already existing, then update section to In Progress and display error banner
- Avoid user from using save and navigate to navigate to Review page with invalid data
**TICKETS**
[CRDCDH-398](https://tracker.nci.nih.gov/browse/CRDCDH-398)

CRDCDH-398 Unique Study Abbreviation

---

src/components/Questionnaire/FundingAgency.tsx
src/components/Questionnaire/ReviewDataListing.tsx
src/components/Questionnaire/ReviewDataListingProperty.tsx
src/components/Questionnaire/ReviewFileTypeTable.tsx
src/components/Questionnaire/ReviewSection.tsx
src/content/questionnaire/sections/Review.tsx

**OVERVIEW**
This PR aims to add Id's to elements containing content in the Review page
**TICKETS**
[CRDCDH-437](https://tracker.nci.nih.gov/browse/CRDCDH-437)

CRDCDH-437 Adding Id's to Review page

---

src/components/Contexts/AuthContext.tsx

fixing login issues

---

src/content/index.tsx

Changing landing page text implementing ticket 464.

changing landing page text

---

src/config/CancerTypesConfig.ts

**OVERVIEW**
This PR removes trailing letters from a specific cancer type.
**TICKETS**
[CRDCDH-463](https://tracker.nci.nih.gov/browse/CRDCDH-463)

CRDCDH-463 Removing trailing letters in Cancer Type

---

src/components/DataSubmissions/DataSubmissionUpload.tsx
src/components/DataSubmissions/LinkTab.tsx
src/components/DataSubmissions/RadioInput.tsx
src/content/dataSubmissions/DataSubmission.tsx

**OVERVIEW**
This PR aims to add upload actions to the Data Submission Dashboard. Mostly UI work, and the upload process is simulated with a success banner afterwards.
**TICKETS**
[CRDCDH-16](https://tracker.nci.nih.gov/browse/CRDCDH-16)
**NOTE**
This PR does not satisfy the ticket fully. It will need to replace Mock API with real API and also some other adjustments.

CRDCDH-16 Data Submission Dashboard Upload

---

src/content/users/ProfileView.tsx

Additional changes to UX QA. 
Comments:
- 37 – Changes to alignment
- 51 – New color on save button

CRDCDH-351 Incorporate new/additional changes

---

src/components/Questionnaire/TextInput.tsx
src/content/questionnaire/sections/B.tsx

This ticket implements ticket 478. 
It autocapitalizes the program and study abbreviation in section B of the questionnaire.

auto-capitalize abbreviations in section b

---

src/content/dataSubmissions/DataSubmissionsListView.tsx

This pr adds CCDI as an option for data commons parameter when creating a data submission, as required in ticket 525.

Crdcdh 525

---

src/components/DataSubmissions/DataSubmissionBatchTable.tsx
src/components/DataSubmissions/PaginationActions.tsx
src/content/dataSubmissions/DataSubmission.tsx
src/content/dataSubmissions/DataSubmissionActions.tsx
src/graphql/index.ts
src/graphql/listBatches.ts
src/types/Submissions.d.ts

**OVERVIEW**
This PR aims to update the Batch table in Data Submission Dashboard with real BE API.
**TICKETS**
[CRDCDH-312](https://tracker.nci.nih.gov/browse/CRDCDH-312)
**NOTE**
Currently BE is fixing bug where all batches from different submissions are returned for the "Submitter" role

CRDCDH-312 Submission Batch Table

---

src/components/DataSubmissions/DataSubmissionUpload.tsx

**OVERVIEW**
This PR aims to fix the popup banner when an upload fails. Beforehand, the upload would should failed then show success instead of just failed. Also, now it shows the correct number of failed files.
**TICKETS**
[CRDCDH-16](https://tracker.nci.nih.gov/browse/CRDCDH-16)

CRDCDH-16 Upload fail validation fix

---

src/components/DataSubmissions/DataSubmissionUpload.tsx

**OVERVIEW**
This PR aims to filter out any file that is not tsv after being selected
**TICKETS**
[CRDCDH-566](https://tracker.nci.nih.gov/browse/CRDCDH-566)
**NOTE**
- Pending confirmation they want to handle it like this

CRDCDH-566 Submission Upload only accept tsv files

---

src/config/DataCommons.ts

Changing data commons from ccdi to icdc to match updated requirements.

ccdi -> icdc

---

src/config/DataCommons.ts
src/types/DataModelNavigator.d.ts

This PR extends the CRDCDH-18 implementation to support the ICDC Data Model as well. 
- Add ICDC model configuration
- Everything else is handled within https://github.com/CBIIT/crdc-datahub-models and PR #176 
> **Note**: Your local environment should define `REACT_APP_DEV_TIER` as `dev2`
https://tracker.nci.nih.gov/browse/CRDCDH-550

CRDCDH-550 ICDC Data Model Configuration

---

src/content/dataSubmissions/DataSubmissionActions.tsx

This PR aims to add Submit button to Withdrawn status.
- Added Withdrawn status to allowed statuses for Submit
- **NOTE:** The UI is done, but the BE will need to allow this action to occur
[CRDCDH-615](https://tracker.nci.nih.gov/browse/CRDCDH-615)

CRDCDH-615 Added Submit button Withdrawn status 

---

Dockerfile

Updated Dockerfile with updated version of node

Node update

---

Dockerfile

Updated Dockerfile with version nginx:1.25.3-alpine3.18-slim

fix: CVE-2023-5363⁠ and CVE-2023-5678

---

src/content/dataSubmissions/DataSubmissionsListView.tsx
src/graphql/listSubmissions.ts

This PR aims to add modelVersion to Data Submission List table.
- Added modelVersion to query
- Added modelVersion to table
[CRDCDH-676](https://tracker.nci.nih.gov/browse/CRDCDH-676)

CRDCDH-676

---

src/content/dataSubmissions/DataSubmission.tsx
src/content/dataSubmissions/DataSubmissionActions.tsx
src/graphql/submissionAction.ts

Added input field to provide rejection comment when rejecting a submission.
- Reused styling for input and rejection comment as questionnaire 
- Comment is required
- Max 500 chars
[CRDCDH-728](https://tracker.nci.nih.gov/browse/CRDCDH-728)

CRDCDH-728 Submission Reject comment

---

src/content/dataSubmissions/ErrorDialog.tsx

Made some small adjustments while testing out the Error Dialog.
- Modified word break to break on word instead of break all to avoid confusion
- Excluded the Issue/Error count from the scrolling, so that it is always visible
[CRDCDH-552](https://tracker.nci.nih.gov/browse/CRDCDH-552)

CRDCDH-552 Small fixes

---

src/content/dataSubmissions/QualityControl.tsx

Minor PR to adjust the Data Submission Validation Results table.
- Remove Validation Type column
- Node ID is renamed to Submitted Identifier
CRDCDH-810

CRDCDH-810 Update Validation Results table

---

src/content/dataSubmissions/QualityControl.tsx

PR to remove the CRDC_ID column from the QC table. It was used for testing only.
N/A
CRDCDH-846

CRDCDH-846 Remove `CRDC_ID` column

---

src/graphql/submissionQCResults.ts
src/types/Submissions.d.ts

Removing CRDC_ID from FE implementation completely per Ming request.
N/A
CRDCDH-846

Remove CRDC_ID from Submission Schema

---

Dockerfile

updated to node v.20 and nginx 1.25.4

---

package-lock.json
src/config/DataCommons.ts

Combined PR to address 508 audit issues identified in CRDCDH-861 (colors) and CRDCDH-865 (interactive controls)
- Upgrade Model Navigator to 1.1.27
- Update color schemes for
- Facet Search > Filter By Property > All count values (e.g. "No **221**")
- Facet Search > Search Term > "Clear History" button
- Facet Search + Graph View > "Clear Search Result" button
- Graph/Table tabs > Inactive tab button
- Update improper nesting of interactive controls in Facet Search (Checkbox nested inside a button)
CRDCDH-861
CRDCDH-865

CRDCDH-861/CRDCDH-865 DMN 508 Audit Issues

---

src/content/dataSubmissions/QualityControl.tsx
src/graphql/getSubmission.ts
src/graphql/submissionQCResults.ts
src/types/Submissions.d.ts

Updated the submissionQCResults and getSubmission queries and types to fix DEV.
FE changes in [CRDCDH-852](https://tracker.nci.nih.gov/browse/CRDCDH-852) still requires further changes and discussion
This PR aims to sync up with the BE changes in [CRDCDH-904](https://tracker.nci.nih.gov/browse/CRDCDH-904)
N/A

Update submissionQCResults and getSubmission queries and types

---

.github/workflows/lint.yml
.github/workflows/test.yml

Split CI jobs and upgrade Node version

---

.github/workflows/lint.yml
.github/workflows/test.yml
src/components/Contexts/AuthContext.test.tsx
src/components/Contexts/FormContext.tsx
src/components/Organizations/StudyTooltip.tsx
src/content/dataSubmissions/QualityControl.tsx
src/content/organizations/ListView.tsx
src/content/organizations/OrganizationView.tsx
src/content/questionnaire/sections/B.tsx
src/graphql/getSubmission.ts
src/graphql/submissionQCResults.ts
src/types/ApprovedStudies.d.ts
src/types/Submissions.d.ts
src/utils/formUtils.test.ts
src/utils/formUtils.ts
src/utils/statisticUtils.test.ts
src/utils/statisticUtils.ts

Sync 3.0.0 (PMVP-M1) with 2.1.0 (MVP2-M3)

---

src/components/DataSubmissions/DataSubmissionSummary.tsx
src/components/DataSubmissions/GenericTable.tsx
src/content/dataSubmissions/DataSubmissionsListView.tsx
src/graphql/listSubmissions.ts

Added Submission Type/Intention in Data Submission List and Data Submission Dashboard.
- Updated listSubmissions query to include `intention`
- Added `Type` column in Data Submission List table with the value as the Submission Type/Intention
- Added Submission Type in the Summary section in the Data Submission Dashboard
- Fixed small accessibility issue with the text in an empty table
[CRDCDH-923](https://tracker.nci.nih.gov/browse/CRDCDH-923)

CRDCDH-923 Displaying Submission Type/Intention

---

package-lock.json
src/components/Questionnaire/SectionGroup.tsx
src/config/SectionMetadata.tsx
src/content/dataSubmissions/DataSubmission.tsx
src/content/dataSubmissions/QualityControl.tsx
src/content/questionnaire/sections/D.tsx
src/content/questionnaire/sections/Review.tsx

Sync 3.0.0 (PMVP-M1) with 2.1.0 (MVP2-M3) 

---

src/components/DataSubmissions/LegendItem.tsx
src/components/DataSubmissions/StatisticLegend.tsx

Added header in legend section and updated the styling to match new design.
> [!Note]
> Used wording on design instead of ticket as this was discussed in meeting
[CRDCDH-1048](https://tracker.nci.nih.gov/browse/CRDCDH-1048)

CRDCDH-1048 Added header in legend section

---

src/content/dataSubmissions/DataSubmission.tsx

Disabled submit when any batch has an "Uploading" status.
N/A
[CRDCDH-1068](https://tracker.nci.nih.gov/browse/CRDCDH-1068)

CRDCDH-1068 Disable submit when uploading batches exist

---

src/content/dataSubmissions/DeleteDialog.tsx

Updated delete dialog text.
N/A
[CRDCDH-1092](https://tracker.nci.nih.gov/browse/CRDCDH-1092)

CRDCDH-1092 Update Delete dialog text

---

src/content/dataSubmissions/CreateDataSubmissionDialog.tsx

Updated the validation for the "Submission Name" input field to trim the whitespace first.
> [!Note]
> This is the PMVP implementation for this fix. This required a different implementation due to refactoring in `3.0.0` branch.
> MVP2-M3 fix implemented in #354
[CRDCDH-1080](https://tracker.nci.nih.gov/browse/CRDCDH-1080)

CRDCDH-1080 PMVP Updated Submission Name input validation to trim whitespace

---

src/content/dataSubmissions/DeleteDialog.tsx

Minor change to CRDCDH-1091, the "Remove" metadataIntention dialog needed some text updates to reflect new terminology. 
N/A
CRDCDH-1091

CRDCDH-1091 Update delete dialog text

---

src/components/DataSubmissions/DataSubmissionUpload.tsx
src/content/dataSubmissions/DeleteDialog.tsx
src/types/Submissions.d.ts

This PR migrates the 3.0.0 changes introduced in #356 and #363 to 2.1.0.
> [!NOTE]
> These changes should be manually discarded when merging 2.1.0 into 3.0.0
- Copy changes from
- 46bf48554c3bebd6c63229d8588b7283561b7dea
- 6b1e95a25a7c860cca8a6e5b8e8b0ffffe063fed
CRDCDH-1091

CRDCDH-1091 Batch Intention Label Update (2.1.0)

---

src/components/Questionnaire/TextInput.tsx
src/content/questionnaire/sections/B.tsx

Increased Section B Program Title character limit to 100, and updated Program Description and Study Description to be resizable inputs. 
- Updated Program title character limit from 50 => 100
- Updated Program Description and Study Description to be resizable inputs
- Updated Text input component to allow infinite vertical resizing
- Set a minHeight when resizing is available so that it cannot be resized smaller than the original, this required some overwriting of MUI styling
[CRDCDH-1113](https://tracker.nci.nih.gov/browse/CRDCDH-1113)

CRDCDH-1113 UAT: Section B updates and resizing multiline inputs

---

Dockerfile

Modified Dockerfile to add the build use fnl base image
N/A
DEVOPS-278

Modified Dockerfile to add the build use fnl base image

---

src/components/DataSubmissions/BackButton.tsx
src/components/DataSubmissions/DataSubmissionSummary.tsx
src/components/DataSubmissions/LinkTab.tsx
src/components/DataSubmissions/MetadataUpload.tsx
src/components/DataSubmissions/ValidationControls.test.tsx
src/components/DataSubmissions/ValidationControls.tsx
src/components/Questionnaire/Repository.tsx
src/components/Questionnaire/ReviewDataListingProperty.tsx
src/components/Questionnaire/TextInput.tsx
src/content/dataSubmissions/DataSubmission.tsx
src/content/dataSubmissions/DataSubmissionActions.tsx
src/content/dataSubmissions/ErrorDialog.tsx
src/content/dataSubmissions/FileListDialog.tsx
src/content/dataSubmissions/QualityControl.tsx
src/content/organizations/OrganizationView.tsx
src/content/questionnaire/sections/B.tsx
src/content/questionnaire/sections/C.tsx
src/content/questionnaire/sections/D.tsx
src/content/questionnaire/sections/Review.tsx
src/utils/dataValidationUtils.ts

PR to sync the recent changes from 2.1.0 into 3.0.0

Sync `2.1.0` with `3.0.0`

---

Dockerfile

added fnl base image to Dockerfile
N/A
N/A

added fnl base image to Dockerfile

---

src/components/DataSubmissions/DataSubmissionUpload.tsx

This PR addresses UAT feedback that the metadata upload status message is misleading.
N/A
CRDCDH-1176

CRDCDH-1176 Change Metadata Upload Alert

---

src/components/Carousel/index.tsx
src/components/DataSubmissions/MetadataUpload.tsx
src/components/DataSubmissions/ValidationStatistics.tsx
src/content/dataSubmissions/ErrorDialog.tsx
src/content/dataSubmissions/QualityControl.tsx
src/utils/stringUtils.test.ts
src/utils/stringUtils.ts

Sync 3.0.0 with 2.1.0

---

src/components/UploaderConfigDialog/index.tsx

PR for simple changes to the CRDCDH-885 dialog form labels.
- Update the dialog form labels to the new ones in the user story
CRDCDH-885

CRDCDH-885 Update Dialog Input Labels

---

.github/workflows/codeql.yml
.github/workflows/test.yml
.github/workflows/typescript.yml

feat: Add CodeQL action and separate TypeScript action

---

package-lock.json

Fix to force proper list formatting in the exported PDFs
- https://github.com/CBIIT/Data-Model-Navigator/commit/b37f65a9fffae8e4f333fc2bd4df843f0b9a4280
CRDCDH-1187

fix: PDF missing `list` props

---

.gitignore
package-lock.json

Data Navigator Template Names Standardization
- Update `data-model-navigator` package
- `createFileName` in data-model-navigator now checks if the file is a template. If it is, it constructs the expected fileName and returns it.
- https://github.com/CBIIT/Data-Model-Navigator/pull/145

CRDCDH-1132: update data-model-navigator package

---

CHANGELOG.md

This PR just adds a placeholder CHANGELOG.md file until we have an official list of release notes from PM.
> [!NOTE]
> Although the implementation will use the terminology "Release Notes", I'm using CHANGELOG.md as that's the general code repository convention, and the filename is never visible to the end user.
N/A
N/A – Technically it's related to CRDCDH-1532, but an official version will be introduced later.

Add Placeholder CHANGELOG.md

---

src/components/DataSubmissions/DataSubmissionSummary.tsx

This PR removes the term "Request" from the Data Submission History Dialog pre-title.
N/A
CRDCDH-1695

CRDCDH-1695 Change Data Submission History Dialog Pre-Title

---

CHANGELOG.md

This PR updates the placeholder changelog to replace the content with the official changelog provided by PM.
N/A
CRDCDH-1615 (FE Changelog task)
CRDCDH-1635 (PM release notes document)
CRDCDH-1532 (User story)

CRDCDH-1615 Add PM provided CHANGELOG.md

---

package-lock.json

N/A
N/A – See DMN https://github.com/CBIIT/Data-Model-Navigator/commit/f750e2f42f8913b7dfc7a8bdf39c98f2513692b4
CRDCDH-1799
CRDCDH-1751

Upgrade DMN to f750e2f

---

src/components/HistoryDialog/index.tsx
src/components/TruncatedText/index.test.tsx
src/components/TruncatedText/index.tsx
src/content/dataSubmissions/QualityControl.test.tsx
src/content/dataSubmissions/QualityControl.tsx

Update the Validation Results table within a Data Submission to be more compact.
- Added fixed width to the following columns:
- Batch ID
- Severity
- Validated Date
- Truncated the text values in the table with underline, ellipsis, and hover tooltip:
- Node Type
- Submitted Identifier 
- Issues
[CRDCDH-1863](https://tracker.nci.nih.gov/browse/CRDCDH-1863) (Task)
[CRDCDH-1862](https://tracker.nci.nih.gov/browse/CRDCDH-1862) (User Story)

CRDCDH-1863 Validation Results Compact Table

---

package-lock.json
src/components/ErrorBoundary/index.test.tsx
src/components/ErrorBoundary/index.tsx

This PR adds test coverage to the ErrorBoundary component, and includes an updated Model Navigator build that handles node properties without descriptions (a very rare situation). 
N/A – See commit details here https://github.com/CBIIT/Data-Model-Navigator/commit/84e0ab1c4238e1b6c89314f4af959a7af0fba511
CRDCDH-1977

CRDCDH-1977 Fix Model Navigator crash

---

CHANGELOG.md

Replace the 3.1.0 changes with updated descriptions.
N/A
N/A

Update 3.1.0 changes per KC

---

CHANGELOG.md

Update CHANGELOG.md per PM

---

src/components/DataSubmissions/CreateDataSubmissionDialog.tsx
src/components/PansBanner/index.test.tsx
src/components/PansBanner/index.tsx
src/components/Questionnaire/FormContainer.tsx
src/content/questionnaire/sections/A.tsx

Sync 3.2.0 with 3.1.0

---

src/components/Contexts/SubmissionContext.test.tsx
src/components/Contexts/SubmissionContext.tsx
src/components/DataSubmissions/DeleteNodeDataButton.test.tsx
src/components/DataSubmissions/DeleteNodeDataButton.tsx
src/components/DataSubmissions/ExportValidationButton.test.tsx
src/config/SubmitButtonConfig.ts
src/content/dataSubmissions/DataSubmission.tsx
src/content/dataSubmissions/DataSubmissionsListView.tsx
src/graphql/submissionQCResults.ts
src/utils/dataSubmissionUtils.test.ts
src/utils/dataSubmissionUtils.ts

Doing this via a PR since it required several manual resolutions.

Sync pbac-update-user-roles with 3.2.0

---

src/components/HistoryDialog/index.tsx

PR to fix a 508 issue with the HistoryDialog (SR and DS) caused by an outdated dialog background.
N/A
CRDCDH-2152

CRDCDH-2152 Fix HistoryDialog 508 Issue

---

src/components/Questionnaire/ApproveFormDialog.tsx
src/components/Questionnaire/InquireFormDialog.tsx
src/components/Questionnaire/RejectFormDialog.tsx
src/components/Shared/ReviewCommentsDialog.tsx
src/components/StatusBar/StatusBar.test.tsx
src/config/QuestionnaireTooltips.ts

Update the Review Comments dialog to utilize as much height as needed to render the review comments, increase the maximum Review Comments input field heights, and update the Canceled tooltip again.
N/A
CRDCDH-2188

CRDCDH-2188 (V2) Submission Request Review Comments Updates

---

src/components/Shared/ReviewCommentsDialog.tsx

hotfix: incorrect minimum height specified

---

src/content/users/ProfileView.tsx

fix: Account Status is not at the bottom of the form

---

src/components/Contexts/FormContext.tsx
src/content/questionnaire/sections/A.tsx
src/content/questionnaire/sections/Review.tsx

Added the `ORCID` property back to the Submission Request form in the PI section as well as in the Review section.
N/A
[CRDCDH-2291](https://tracker.nci.nih.gov/browse/CRDCDH-2291) (Task)
[CRDCDH-2065](https://tracker.nci.nih.gov/browse/CRDCDH-2065) (US)

CRDCDH-2291 Re-enable ORCID in the Submission Request form

---

src/config/CellLineModelSystemConfig.ts

Add cell lines and model systems tooltips.
N/A
CRDCDH-2292

CRDCDH-2292 Add tooltips

---

src/content/dataSubmissions/DataSubmissionsListView.tsx
src/content/questionnaire/ListView.tsx

Updated the text displayed within the Data Submission List table and Submission Request List table when there is no results to display.
N/A
[CRDCDH-2295](https://tracker.nci.nih.gov/browse/CRDCDH-2295) (Task)
[CRDCDH-2294](https://tracker.nci.nih.gov/browse/CRDCDH-2294) (US)

CRDCDH-2295 Updated empty table placeholder text for Data Submission List and Submission Request List

---

package-lock.json

This PR updates our version of Data Model Navigator to support new Data Dictionary exports:
- TSV
- JSON
Additionally, for both the above types, and the existing PDF type, we now support exporting of only Required properties, or all of them.
> [!NOTE]
> The styling between the Figma mockup and the actual implementation differs slightly due to integration issues between DMN and CRDC. The design may not be 100% finalized yet, so there may be another PR in the future if needed.
- See Model Navigator changes here: https://github.com/CBIIT/Data-Model-Navigator/compare/84e0ab1c4238e1b6c89314f4af959a7af0fba511...b5d4f1873e646784b35dcc7a3c8eebc83f768bb3
CRDCDH-2190 (Primary task)
CRDCDH-2191 (Filename task)
CRDCDH-2069 (Userstory)

CRDCDH-2190 Model Navigator – TSV, JSON, and PDF Dictionaries

---

src/content/organizations/Controller.test.tsx
src/content/organizations/Controller.tsx
src/content/organizations/OrganizationView.tsx

This PR adds asterisks to required fields on the Edit/Add program page, and has some minor QoL changes.
- Add asterisks to Program Name, Abbreviation, and Status on the Add/Edit Program pages
- Fix the Add/Edit title using the term Organization instead of Program
- Add test coverage for the Controller
CRDCDH-2301

CRDCDH-2301 Add Asterisks to Edit Program Page

---

src/components/CancelApplicationButton/index.test.tsx
src/components/Contexts/FormContext.test.tsx
src/config/AuthPermissions.test.ts
src/config/InitialValues.ts
src/content/questionnaire/ListView.tsx
src/graphql/listApplications.ts
src/types/Application.d.ts
src/utils/stringUtils.test.ts
src/utils/stringUtils.ts

Updated Submission Request List table to include versioning.
> [!WARNING]
> Currently sorting by the version column is broken. The BE claims that it will be resolved when the real SR versions are restored. ([CRDCDH-2309](https://tracker.nci.nih.gov/browse/CRDCDH-2309))
- Retrieved the version from the application, and extracted the major and minor versions to ensure it is in the correct format
- Displayed the version in the Submission Request List table as a column
[CRDCDH-2267](https://tracker.nci.nih.gov/browse/CRDCDH-2267) (Task)
[CRDCDH-2205](https://tracker.nci.nih.gov/browse/CRDCDH-2205) (US)

CRDCDH-2267 Submission Request version tracking

---

src/components/UploaderToolDialog/index.test.tsx
src/components/UploaderToolDialog/index.tsx

Updated design for displaying the CLI version within the Uploader Tool Dialog.
N/A
[CRDCDH-2268](https://tracker.nci.nih.gov/browse/CRDCDH-2268) (Task)
[CRDCDH-2274](https://tracker.nci.nih.gov/browse/CRDCDH-2274) (US)

CRDCDH-2268 Update Uploader Tool Dialog design

---

src/content/organizations/OrganizationView.tsx

fix: Missing effect dependency

---

CHANGELOG.md

N/A
N/A
CRDCDH-2263 (Task)
CRDCDH-2207 (US)

Add draft 3.2.0 changes

---

CHANGELOG.md

CRDCDH-2263 Decrease subheading level by 1

---

CHANGELOG.md

Update the incorrect 3.2.0 release date, change the "Data Model Enhancements" title to "Data Model Navigator Enhancements", and fix the incorrect SR form version listed
N/A
N/A

Fix 3.2.0 Release Date and Change Section Title

---

src/content/studies/StudyView.tsx

While adding/editing a study, the Primary Contact required at least one selection. This has been updated to allow no selection. If no selection, it will default to "Same as the Program Primary Contact" being checked.
N/A
[CRDCDH-2449](https://tracker.nci.nih.gov/browse/CRDCDH-2449) (Bug)

CRDCDH-2449 Bug: Update Study Primary Contact to be optional

---

CHANGELOG.md

CRDCDH-2573 Add 3.2.1 changes

---

Dockerfile
package-lock.json

vulnerability patching

---

.github/workflows/build-fe.yaml.old

Supersedes #673 
N/A
CRDCDH-2582

CRDCDH-2582 Deployment Pipeline Via GitHub Actions

---

src/content/OperationDashboard/DashboardView.tsx

Minor PR to enable the reset icon in the QuickSight toolbar.
N/A
CRDCDH-2599 (Task)
CRDCDH-2565 (US)

CRDCDH-2599 QuickSight Dashboard Reset Icon

---

src/content/dataSubmissions/DataSubmissionsListView.tsx

PR to rename the "DM Version" to "Model Version" per user feedback.
N/A
CRDCDH-2604 (Task)

CRDCDH-2604 DM Version column rename

---

src/components/DataSubmissions/CreateDataSubmissionDialog.tsx
src/components/GenericTable/index.tsx
src/components/StatusBar/components/HistorySection.tsx
src/content/questionnaire/ListView.tsx

Additional 508 issues resolved with the Submission Request List table "Conditional Approval" on the alternate TR background (red on blue).
N/A
CRDCDH-2502

CRDCDH-2502 508 Fixes

---

.github/workflows/build-fe.yaml

Supersedes #698
N/A
CRDCDH-2582

CRDCDH-2582 Build Pipeline Via GitHub Actions

---

src/components/AdminPortal/Studies/ApprovedStudyFilters.test.tsx
src/components/AdminPortal/Studies/ApprovedStudyFilters.tsx
src/components/StudyList/index.tsx
src/components/SummaryList/index.stories.tsx
src/components/SummaryList/index.tsx
src/components/TruncatedText/index.tsx
src/content/organizations/ListView.tsx
src/content/studies/Controller.test.tsx
src/content/studies/Controller.tsx
src/content/studies/ListView.tsx
src/content/studies/StudyView.tsx
src/graphql/listApprovedStudies.ts

Updated the Manage Studies List page to include additional table columns and filters. Also, truncated the table values further to avoid table wrapping. 
> [!NOTE]
> Sorting of the new columns is not yet ready on BE. Also, the "NA" program is still being worked on.
- Added Program and Primary Contact columns to table. The program column will list the first + additional programs in a tooltip
- Added an additional "Program" dropdown filter to filter by a single program, including "All" and "NA". The "NA" program will display all the studies that aren't assigned to any program
- Truncated table values to avoid table wrapping
[CRDCDH-2534](https://tracker.nci.nih.gov/browse/CRDCDH-2534)

CRDCDH-2534 Manage Studies List Updates

---

.github/workflows/build-fe.yaml
CHANGELOG.md

3.2.2 Release Sync

---

src/components/CreateApplicationButton/index.stories.tsx
src/components/CreateApplicationButton/index.test.tsx
src/components/CreateApplicationButton/index.tsx
src/content/questionnaire/ListView.test.tsx
src/content/questionnaire/ListView.tsx

This PR abstracts the Submission Request create button, adds a confirmation dialog step, and introduces some general QoL changes.
- Componentize the SR Create button
- Create a storybook for the SR create button
- Update related integration tests for changes
CRDCDH-2699 (Task)
CRDCDH-2629 (US)

CRDCDH-2699 Submission Request Creation – Confirm Step

---

src/components/NodeComparison/ComparisonTable.test.tsx
src/components/NodeComparison/ComparisonTable.tsx
src/components/NodeComparison/__snapshots__/ComparisonTable.test.tsx.snap

Minor change to node comparison changes – Apply a grayed background to unchanged columns
N/A
CRDCDH-2719 (Task)

CRDCDH-2719 fix: Unchanged columns missing background color

---

src/components/PansBanner/index.test.tsx
src/components/PansBanner/index.tsx

revert: OMB expiration update

---

Dockerfile

Updates Node.js base image to 22.17.0

---

src/content/DataExplorer/ListView.tsx

Changed default sorting to asc instead of desc
N/A
[CRDCDH-2789](https://tracker.nci.nih.gov/browse/CRDCDH-2789) (Task)
[CRDCDH-2741](https://tracker.nci.nih.gov/browse/CRDCDH-2741) (US)

CRDCDH-2789 Data Explorer - Fix default sorting

---

.github/workflows/copilot-setup-steps.yml

Initial setup of copilot steps

Add copilot setup steps

---

.github/workflows/build-fe.yaml
.github/workflows/copilot-setup-steps.yml

Sync 3.4.0 with main

---

.github/copilot-instructions.md

docs: Init copilot instructions draft

---

.github/workflows/copilot-setup-steps.yml

This reverts commit 2768f8a8285694d7e352bd3652d87dc0e1ab2df7.
N/A
N/A
N/A

Revert "MCP Setup (#792)"

---

src/content/questionnaire/sections/Review.tsx

Forgot to change the GPA Name label in the Review section to reflect the finalized label in section C. Also, increased the sizing to take the entire row.
N/A
[CRDCDH-3113](https://tracker.nci.nih.gov/browse/CRDCDH-3113) (US)

CRDCDH-3113 [Bug]: Fix Review section GPA Name label and width

---

src/classes/Excel/A/SectionA.ts

Additional Contacts institution field only had length validation, but didn't have the institution dropdown.
N/A
CRDCDH-3063

fix: Additional Contact missing institution dropdown

---

src/classes/Excel/B/Columns.ts
src/classes/Excel/D/Columns.ts
src/classes/Excel/D/SectionD.ts

The Targeted Submission Date cell validation was pointing at the wrong cell causing it always to fail. Also, fixed annotations to reflect info tooltips in sections B & D
N/A
[CRDCDH-3063](https://tracker.nci.nih.gov/browse/CRDCDH-3063)

fix: Date validation pointing at wrong cell and update annotations

---

package-lock.json

This PR bumps the Model Navigator dependency to v1.6.0, which sorts the Acceptable Values lists alphabetically everywhere (table view, TSV/JSON exports, etc).
N/A
CRDCDH-3070 (Task)
CRDCDH-3013 (US)

CRDCDH-3070 Sort DMN Acceptable Values Alphabetically

---

src/components/DataSubmissions/CreateDataSubmissionDialog.test.tsx
src/graphql/getMyUser.ts

Fixes an issue where the getMyUser query is missing the isPendingGpa property, causing the dialog to not disable the create button correctly.
N/A
CRDCDH-3199

CRDCDH-3199 Fix query missing required study property

---

src/classes/Excel/Instructions/Content.ts

PR to address pasting into excel by adding a note on how to do it. I'm open to other verbiage on the note if it isn't clear. 
> [!NOTE]
> This potentially could be solved by adding worksheet protections, but it's super tedious. I left more details in the bug.
N/A
CRDCDH-3263

CRDCDH-3263 Add a FAQ for pasting into fields

---

src/content/DataExplorer/ListView.tsx

Change the last portion of the banner text to clarify what data explorer is.
N/A
CRDCDH-3289 (task)
CRDCDH-3286 (US)

CRDCDH-3289 Data Explorer banner text update
