CBIIT/crdc-datahub-ui

src/content/questionnaire/FormView.tsx, src/layouts/index.tsx
This PR covers ticket [CRDCDH-92](https://tracker.nci.nih.gov/browse/CRDCDH-92) to support the redesigned form layout.
Old layout:
New layout:
=> CRDCDH-92 Restructure FormView to support redesign

src/components/Header/components/NavbarDesktop.tsx, src/config/globalHeaderData.tsx, src/content/questionnaire/sections/B.tsx
This pr addresses requirements from Yizhen about the navbar underline tracking current navigation.
- The navbar section where you are navigated to a subsection in, will be underlined blue now.
Also addresses an issue brought up by Alex, where clicking a navbar section would shift the navbar.
- This no longer happens, and each section is static.
=> Adding underline styles, and fixing dropdown style

src/components/StatusBar/components/HistorySection.tsx, src/components/StatusBar/components/StatusSection.tsx
Minor verbiage update to the Status Bar dialogs (removing visual usage of "Questionnaire" naming) per the updated comments in [CRDCDH-37](https://tracker.nci.nih.gov/browse/CRDCDH-37).
=> CRDCDH-37 Update Status Bar verbiage

src/content/questionnaire/FormView.tsx, src/content/questionnaire/sections/C.tsx
**Overview**
This PR is to hide validation when saving from unsaved changes dialog. Also, I fixed issue with Cell Line & Model Systems to persist state as the value was changed to initial value when dialog appeared.
=> CRDCDH-80 Hide validation when saving from dialog

src/config/InitialValues.ts, src/content/questionnaire/sections/B.tsx, src/types/Application.d.ts
This adds the cdGaP section in form section B.
- A switch for indicating if the study is registered with cdGaP
- A textbox that appears if the switch is correct.
- Added fields to Application.d.ts to accompany these fields. **we will need to update graphql schema**
=> Implementing ticket 134

src/components/Header/HeaderTabletAndMobile.tsx, src/components/Header/components/NavbarDesktop.tsx, src/content/index.tsx, src/router.tsx
This PR implement ticket 148, adding auth check on URL's. It currently protects the Submission Requests and Data Submissions tabs, although protecting others would be easy.
This also resolves ticket 191 by adding navigation to home page on every available logout button.
This also resolves ticket 196 by adding functionality to open external links in a new tab from the navigation bar.
**This does not add navigation to the logout function provided by authContext. Every logout button located in the header just navigates to home and displays the logout banner. If you are adding other logout buttons, they will not automatically navigate.**
=> Crdcdh 148-191-196

src/components/Questionnaire/CheckboxInput.tsx, src/content/questionnaire/FormView.tsx
**OVERVIEW**
This PR is to fix an infinite loop caused by re-renders and formMode recalculation. Moved to a useEffect instead to avoid this issue. Also hid the blocker from displaying while redirecting unauthorized user. Additionally, I fixed small cursor issue with readOnly checkboxes that I noticed while testing.
**TICKET**
[CRDCDH-192](https://tracker.nci.nih.gov/browse/CRDCDH-192)
=> CRDCDH-192 Fixed unauthorized infinite loop

src/components/Header/HeaderTabletAndMobile.tsx, src/components/Header/components/NavbarDesktop.tsx, src/config/globalHeaderData.tsx, src/content/index.tsx
This pr removes a redundant authorization check. Originally the code checked if you were authorized when clicking on the navbar to a protected page. Now, with auth check on the protected page, there is no need for auth check on navbar.
This also adds the second login button Kailing requested inside the login dialog box.
=> Crdcdh refine auth check

src/content/questionnaire/FormView.tsx
Updates the Questionnaire Form progressbar to match the offset alignment in the Figma mockup
Old:
New:
=> CRDCDH-38 Fix top alignment

src/components/StatusBar/components/HistorySection.tsx, src/components/StatusBar/components/StatusSection.tsx
This updates the Submission Request Form status bar to add more margin between the Form Status / Form Date and the action buttons next to it. 
Old:
New:
=> CRDCDH-37 Fix margin between Status/Date and buttons

src/components/Contexts/FormContext.test.tsx, src/components/Contexts/FormContext.tsx
This updates the "PI Autofill" functionality to execute ONLY if Section A is not started.
NOTE: This is a slower approach because the form has to wait until the `getApplication` query resolves before executing the `getMyLastApplication` query–but this is implemented exactly per the requirements.
=> CRDCDH-132 Autofill PI data only when Section A is not started

src/components/Questionnaire/AutocompleteInput.tsx, src/components/Questionnaire/DatePickerInput.tsx, src/components/Questionnaire/FormGroupCheckbox.tsx, src/components/Questionnaire/RadioYesNoInput.tsx, src/components/Questionnaire/SelectInput.tsx, src/components/Questionnaire/SwitchInput.tsx, src/components/Questionnaire/TableTextInput.tsx, src/components/Questionnaire/TextInput.tsx, src/config/AccessTypesConfig.ts, src/config/CellLineModelSystemConfig.ts, src/content/questionnaire/FormView.tsx, src/content/questionnaire/sections/D.tsx, src/types/Globals.d.ts, src/utils/formUtils.ts, src/utils/validationUtils.ts
This PR changes all required input components to display validation on save only, and clears the error state on change. Additionally, it removes the visible HTML5 validation alert (see below).
=> CRDCDH-136 Validate inputs on save

src/components/Questionnaire/RadioYesNoInput.tsx, src/components/Questionnaire/SectionGroup.tsx, src/components/Questionnaire/SwitchInput.tsx, src/components/Questionnaire/TableFileTypeAndExtensionInput.tsx, src/components/Questionnaire/TableTextInput.tsx, src/config/InitialValues.ts, src/content/index.tsx, src/content/questionnaire/sections/D.tsx
This is to update the styling for the login dialog according to kailing's requests.
Requested:
Chaged to:
This also implements changes kailing wanted for ticket CRDC-45.
=> CRDC-45 Section D updates and login styling

src/components/Questionnaire/AdditionalContact.tsx, src/content/questionnaire/sections/A.tsx, src/utils/formUtils.test.ts, src/utils/formUtils.ts
This PR captures changes to Section A per requirements changes outlined in [CRDCDH-33](https://tracker.nci.nih.gov/browse/CRDCDH-33).
Specifics:
- Changed "Email address" labels to just "Email"
- Same as Principal Investigator checkbox hides the Primary Contact input fields
- Phone numbers can now contain numeric, dash, and spaces
- Added custom email validator (for some reason emails missing a TLD was valid..?)
- Use custom error message for emails (to indicate they're invalid)
=> CRDCDH-33 Update for Requirements changes

src/components/PageBanner/index.tsx, src/content/questionnaire/FormView.tsx, src/content/questionnaire/ListView.tsx
This PR updates CRDCDH-54 Questionnaire List View for the newest requirements.
Specifically:
- Reduced space between the create submission req. button
- Added pagination result count options 5, 10, 20, 50
**spacing before**:
**spacing after**:
> **Warning**: These changes differ from the Figma mockup per request.
=> CRDCDH-54 Update for newest requirements

src/components/ProgressBar/ProgressBar.test.tsx, src/components/ProgressBar/ProgressBar.tsx, src/components/Questionnaire/ApproveFormDialog.tsx, src/components/Questionnaire/RejectFormDialog.tsx, src/content/questionnaire/FormView.tsx, src/content/questionnaire/sections/Review.tsx, src/content/questionnaire/sections/hooks/useFormMode.ts, src/graphql/getMyUser.ts, src/lib/AuthUser.ts, src/types/Application.d.ts, src/types/Auth.d.ts, src/utils/formModeUtils.test.ts, src/utils/formModeUtils.ts, src/utils/index.ts
**OVERVIEW**
This PR aims to expand the amount of variables to calculate the form mode, rather than just "User" and "FederalLead" roles and form status. I separated the logic for calculating the form mode into its own utility file where I could create tests for it easier and also simplify the useFormMode hook itself.
- Added organization to getMyUser query and User type
- Separated useFormMode hook logic into separate utility file to make it testable
- Created detailed tests for each role, orgRole, formStatus, who submitted the form, which organization the submission belongs to, which organization the user belongs to (if any), etc.
- Updated Approve/Reject form dialog to maintain internal state for review comment and only pass the value onSubmit. Previously, it was causing the parent to …
=> CRDCDH-49 Form Auth Update

src/components/Questionnaire/TableTextInput.tsx, src/content/questionnaire/sections/D.tsx
This pr fixes a bug where non-numerical characters could be typed into the file count input in the table in section D.
Now, only positive integers can be typed into the input, as requried.
=> fixing positive integer input

src/components/Contexts/FormContext.test.tsx, src/components/Contexts/FormContext.tsx, src/components/StatusBar/components/HistorySection.tsx, src/content/questionnaire/FormView.tsx, src/graphql/saveApplication.ts
This PR is tangentially related to ticket CRDCDH-37 and incorporates general bug fixes.
**Specifics**:
- Fetches BE-populated fields and updates them in our local state on save. This will allow the Status Bar to always represent the BE stored application details (e.g. History / Status).
- Fixes a bug with overwriting the initial values for the section status array, which carries over between applications.
- Fixes a bug referencing the status of "Complete" instead of "Completed" when determining if we should fetch past data for Questionnaire Section A
=> CRDCDH-37 Update cached state on save

src/content/questionnaire/ListView.tsx, src/content/users/Controller.tsx, src/content/users/ProfileView.tsx, src/graphql/getMyUser.ts, src/types/Auth.d.ts, src/utils/formModeUtils.test.ts, src/utils/formModeUtils.ts
**OVERVIEW**
This PR aims to reflect changes made to Organizations. Org roles were removed and combined with user role. This updates all of the form mode considerations to only consider user roles, as well as tests. 
**TICKETS**
[CRDCDH-49](https://tracker.nci.nih.gov/browse/CRDCDH-49)
**IMPORTANT**
Make sure to pull latest from BE, AuthN, and AuthZ
=> Organization roles update

src/content/users/ProfileView.tsx
This PR updates the CRDCDH-68 SELF Profile editing for requirement updates. Notably,
- Remove "Cancel" (aka reset) button from the page
- Add a "successful profile save" message banner
- Remove the "Edit Pencil" icon next to inputs
=> CRDCDH-68 Update for Requirement changes

src/components/Questionnaire/DatePickerInput.tsx
**OVERVIEW**
This PR aims to create an error when a past date is entered manually through typing in DatePickerInput. Previously, it was only disabled in the calendar popup selection.
**TICKETS**
[CRDCDH-308](https://tracker.nci.nih.gov/browse/CRDCDH-308)
=> CRCDH-308 Prevent past date being entered manually

src/content/users/ListView.tsx
This PR fixes the wrong count variable introduced in #110 and resets the table page on sort/filter change. Also includes changes per Kailing:
=> CRDCDH-178 Fix page on sort/filter

src/components/StatusBar/StatusBar.test.tsx, src/components/StatusBar/components/HistorySection.tsx, src/content/questionnaire/ListView.tsx
This fixes ticket 334 so that the status bar in the questionnaire always displays the last updated date, even if the status is "New".
Also changes status and program columns in the submission table to "N/A" instead of "NA" for consistency.
=> Updating Questionnaire Status Bar to always display last updated date

src/components/Questionnaire/AdditionalContact.tsx, src/components/Questionnaire/AutocompleteInput.tsx, src/content/questionnaire/sections/A.tsx
This PR fixes bug [CRDCDH-336](https://tracker.nci.nih.gov/browse/CRDCDH-336) which causes any `AutocompleteInput` to not validate custom user input.
To replicate the bug:
1. Find a autocomplete input with no value currently set (Important)
2. Type custom text into the field
3. Save
4. See the validation error
The fix:
- Updated the autocomplete input to watch for input within the text field. Any changes in the text field triggers the existing processValue function.
=> CRDCDH-336 Monitor for freeSolo input

src/components/Header/HeaderTabletAndMobile.tsx, src/components/Header/components/NavbarDesktop.tsx, src/config/AuthRoles.ts, src/content/questionnaire/ListView.tsx, src/content/users/Controller.tsx, src/content/users/ListView.tsx, src/types/Auth.d.ts, src/utils/formModeUtils.test.ts, src/utils/formModeUtils.ts, src/utils/profileUtils.test.ts
This PR introduces the renamed User Roles as described exactly in CRDCDH-178/CRDCDH-179/CRDCDH-359. This update is complementary to the backend update and should not be DEPLOYED prior to the BE approval.
=> CRDCDH-359 Update user roles to match BE

src/components/ProgressBar/StatusAdornment.tsx, src/components/Questionnaire/FormContainer.tsx, src/components/Questionnaire/SectionGroup.tsx, src/content/questionnaire/FormView.tsx, src/content/questionnaire/sections/A.tsx
This builds on PR #109 and covers Design QA comments in [CRDCDH-217](https://tracker.nci.nih.gov/browse/CRDCDH-217):
- 22
- 21
- 23
- 20
- 18 – Updated disabled button to `#D9DEE4` per Hannah
- 17 - Updated since it starts from Section A
Comments not addressed:
- Comment 14 – Issue with the screenshot
- Comment 7 – Addressed already
- Comment 3 – Addressed already
=> CRDCDH-217 Design QA changes and fixes

src/components/Questionnaire/TableFileTypeAndExtensionInput.tsx
This addresses ticket 220 which is UX QA for section D of the questionnaire.
Specifically addresses figma comment #13. 
- The box is now as wide as the table column, and the hover color is now #3E7E6D.
Comment #12 is due to a requirement from and the current implementation is correct.
Comment #11 is because coding wise, left is false, and right is true, and I cleared this with Hannah, the current implantation is fine.
Comment #17 is addressed on Alec's CRDC-217 branch.
=> Crdcdh 220 Section D UX updates

src/config/globalFooterData.tsx
This implements ticket 370, changing this:
On the Data Hub footer, replace the "[cdshelpdesk@mail.nih.gov](mailto:+cdshelpdesk@mail.nih.gov)" email with the NCI  [NCIinfo@nih.gov](mailto:NCIinfo@nih.gov) email address.
=> updating footer email link

src/config/FileTypeConfig.ts
Implements ticket 384,
On the Data Types page of the Submission Request form, add "TSV" to the predefined extension list for the Clinical Data Type.
=> Add TSV to clinical data types

src/config/InitialValues.ts, src/config/ProgramConfig.ts, src/content/questionnaire/sections/B.tsx, src/types/Application.d.ts, src/utils/formUtils.ts
**OVERVIEW**
This PR aims to fix a bug where if you select "Other" as an option, but leave the title, abbrev, and desc as empty, then on refresh it will reset to an empty select dropdown. I added "isCustom" property to Program so that it may keep track of this properly and not rely on the values of the program fields below it.
**TICKETS**
[CRDCDH-396](https://tracker.nci.nih.gov/browse/CRDCDH-396)
=> CRDCDH-396 Program "Other" bug fix

src/content/users/ListView.tsx, src/content/users/ProfileView.tsx
This is a UX QA update for User Profile, Edit User, & Manage Users.
**DID NOT ADDRESS**:
* 34 – This is for Navbar QA
* 35 – This is for Navbar QA
* 36 – This is for Navbar QA
* 39 – Effort too high / Impossible with CSS
* 42 – No action item
* 43 – Kailing requested to leave it off
**ADDRESSED**:
* 37
* 38
* 40
* 41
* 44
* 45
* 46
* 47
* 48
* 49
- https://tracker.nci.nih.gov/browse/CRDCDH-351
=> CRDCDH-351 User Management UX QA Changes

src/components/Questionnaire/TableFileTypeAndExtensionInput.tsx, src/components/Questionnaire/TableTextInput.tsx, src/content/index.tsx, src/content/questionnaire/sections/D.tsx
Implements ticket 401, changing the login page text.
On the login page:
Title text "Login to CRDC DataHub" should be changed to "Login to CRDC"
Explanation text should be changed to:  "Please login with a Login.gov account to make a data submission request or to upload data for approved submissions"
=> Crdcdh 401 -  Changing login page

src/components/Questionnaire/TableFileTypeAndExtensionInput.tsx, src/components/Questionnaire/TableTextInput.tsx, src/content/questionnaire/sections/D.tsx
This implements ticket 397. 
It solves the number of files field by putting a cap on the length allowed to be input (10 chars).
I solved the error issue kailing asked by making a custom tooltip, but need approval for it.
=> Adding tooltips to show errors for file type table

src/content/users/ListView.tsx
This fixes a bug which prevents values in disabled select fields from being visible. It also updates the default table sort direction (requirement was introduced after feature was developed).
- https://tracker.nci.nih.gov/browse/CRDCDH-430 – Bug from #111
- https://tracker.nci.nih.gov/browse/CRDCDH-431 – Requirement update
=> CRDCDH-430 Manage Users table fixes

src/components/Contexts/AuthContext.tsx, src/components/GenericAlert/index.tsx, src/components/Header/index.tsx, src/components/InactivityDialog/InactivityDialog.tsx
This implements ticket 433, which add a red banner error msg when the login fails.
This covers the inactive user case, but also covers every login fail.
=> Adding error msg on login fail

src/content/users/ListView.tsx, src/content/users/ProfileView.tsx
This PR updates the User Management UI per [CRDCDH-351](https://tracker.nci.nih.gov/browse/CRDCDH-351).
Comments:
- 37 – Positioned exactly 44px from the banner bottom and 34px from the profile icon right edge
- 44 – Hover background #D5EDE5, selected option background #3E7E6D
- 50 – Doubled the form key:value padding from 20px to 40px
- https://tracker.nci.nih.gov/browse/CRDCDH-351
=> CRDCDH-351 UX QA additional changes

src/components/Contexts/FormContext.tsx, src/content/questionnaire/FormView.tsx
**OVERVIEW**
This PR aims to allow for additional saves to be made even when no changes have been made and the duplicate Study Abbreviation error has occurred. 
- Displays alert banner when unable to save due to duplicate Study Abbreviation
- Prevent user from navigating to another section with Next/Back buttons as well as Progress bar buttons, when user has duplicate Study Abbreviation error 
- Fixed small bug where the "Next" button in section D wouldn't enable when all sections complete in a new submission
**TICKETS**
[CRDCDH-449](https://tracker.nci.nih.gov/browse/CRDCDH-449)
=> CRDCDH-449 Allow additional saves when duplicate Study Abbrev error

src/components/Questionnaire/SubmitFormDialog.tsx, src/content/questionnaire/FormView.tsx, src/content/questionnaire/ListView.tsx
**OVERVIEW**
This PR aims to make small wording adjustments
**TICKETS**
[CRDCDH-467](https://tracker.nci.nih.gov/browse/CRDCDH-467)
[CRDCDH-468](https://tracker.nci.nih.gov/browse/CRDCDH-468)
=> CRDCDH-467 Small wording changes

src/components/DataSubmissions/DataSubmissionBatchTable.tsx, src/components/DataSubmissions/PaginationActions.tsx, src/content/dataSubmissions/DataSubmission.tsx, src/graphql/getDataSubmissionBatchFiles.ts, src/graphql/index.ts
**OVERVIEW**
This PR aims to add the Batch Table to the Data Submission Dashboard. It is currently using Mock API data.
**TICKETS**
[CRDCDH-275](https://tracker.nci.nih.gov/browse/CRDCDH-275)
**NOTE**
This PR does not satisfy the ticket fully. It will need to replace Mock API with real API and also some other adjustments.
=> CRDCDH-312 Data Submission Dashboard Batch Table

src/graphql/getMyUser.ts, src/types/Auth.d.ts, src/utils/formModeUtils.test.ts
The BE removed `curatedOrganizations` from the schema. This PR reflects that change.
=> Remove `curatedOrganizations` from FE

src/content/organizations/ListView.tsx
Fixes issues identified by @Alejandro-Vega:
- In the case that the organization does not have a `status` (e.g. flawed data), we should not crash the app when sorting by that field
To resolve the above issue locally:
> use crdc-datahub
> db.organization.updateMany({}, { $set: { "status": "Active" }})
Other issues:
- Sorting by Primary Contact did not handle `null` values as expected (nulls sorted before values)
Did not address:
- The placeholder for the table view uses the term "users" instead of "organizations". This was updated in #156
=> fix: Handle sorting for null attributes

src/content/users/ListView.tsx
This resolves a bug that occurs when an organization name changes. The `orgName` was being used instead of `orgID` when determining if the org existed in the filter dropdown.
N/A
=> fix: Changing the name of an org breaks Org Dropdown

src/config/SectionMetadata.tsx, src/content/dataSubmissions/DataSubmissionsListView.tsx
This fixes a typo, which is ticket 489.
It also expands the character limit for the dbgap input on creating a data submission.
=> Crdcdh 489

src/components/DataSubmissions/DataSubmissionSummary.tsx, src/content/dataSubmissions/DataSubmissionsListView.tsx, src/graphql/listSubmissions.ts, src/types/Submissions.d.ts
This follows a backend PR to change concierge to conciergeName in the submissions type object since we need conciergeEmail in the type as well.
Merge after: https://github.com/CBIIT/crdc-datahub-backend/pull/124
=> change concierge to conciergeName

src/content/dataSubmissions/DataSubmissionsListView.tsx, src/content/questionnaire/sections/B.tsx
This fixes an ticket 533 with sorting by dbGaPID on data submissions. Also wraps the table cells in data submissions table list view to fit the 50 character dbgapID.
=> fix sorting and dgbap length

src/content/dataSubmissions/DataSubmissionsListView.tsx
This addresses the bug mentioned in ticket 543, where the button should say create instead of submit.
=> CRDCDH-543

src/router.tsx
This pr addresses the bug outlined in 568.
The bug arose because the router was rendering the page regardless of authentication status (and then navigating to home), and the data-submissions page required information that authenticated users have.
This adds logic to make sure the page is only rendered if an authenticated user is clicking on the link.
=> fixing router bug

public/index.html
This implements ticket 547 which is the government shutdown banner.
Adds the government shutdown banner script to our index.html
To test, just change the URL in the include-html src to "https://cbiit.github.io/crdc-alert-elements/banners/government-shutdown-test.html"
=> implement gov shutdown banner

src/content/dataSubmissions/DataSubmissionsListView.tsx
This PR adds null-safe chaining to the data submissions list view, so in case a user's organization doesn't exist, it doesn't crash the app.
Instead of crashing the app, the page loads with no data submissions returned.
=> add nullsafe chaining to dataSubmissionsListView

src/components/SystemUseWarningOverlay/OverlayWindow.tsx
This PR fixes an issue where the Data Model Navigator is overriding our styling for the Government Warning Banner dialog.
To Replicate:
1. Open https://hub-dev2.datacommons.cancer.gov/model-navigator/ICDC
Before:
After:
https://tracker.nci.nih.gov/browse/CRDCDH-619
=> CRDCDH-619 Fix OverlayWindow styling on DMN page

src/content/dataSubmissions/DataSubmissionActions.tsx
This PR aims to update the Submission Actions so that the release button opens a dialog. I had already created it, I simply forgot to call it.
- Instead of Releasing on button click, it will first open a dialog to confirm
[CRDCDH-618](https://tracker.nci.nih.gov/browse/CRDCDH-618)
=> CRDCDH-618 Added missed call to open release dialog

.eslintrc.cjs, public/index.html, public/injectEnv.js, public/js/session.js, src/components/SystemUseWarningOverlay/OverlayWindow.tsx
This PR adds the missing sessionStorage data sync functionality that Bento apps have implemented. The mission functionality causes the Government Warning Banner to appear on every new tab you open, instead of just the first one opened.
- Sync session storage data between open tabs using window storage event listener
- Copied approach from Bento [public/js/session.js](https://github.com/CBIIT/bento-frontend/blob/ce808c12a22a1f111fe94be7112154ccb624cc50/packages/bento-frontend/public/js/session.js#L1-L2)
https://tracker.nci.nih.gov/browse/CRDCDH-619
https://tracker.nci.nih.gov/browse/CRDCDH-144
=> CRDCDH-619 Switch from Session Storage to Cookies

src/components/Header/HeaderTabletAndMobile.tsx, src/components/Header/components/NavbarDesktop.tsx, src/content/users/UploaderToolDialog.tsx
This adds a dialog for the Uploader CLI download links.
- Based off of the API Token dialog per K.C.
- Currently it just provides the GitHub link to the repo
https://tracker.nci.nih.gov/browse/CRDCDH-602
=> CRDCDH-602 Uploader CLI Dialog

src/components/DataSubmissions/DataSubmissionUpload.tsx
This PR aims to update Data Submission upload to allow .txt files 
N/A
[CRDCDH-612](https://tracker.nci.nih.gov/browse/CRDCDH-612)
=> CRDCDH-612 Submission upload allow txt files

src/components/Header/HeaderTabletAndMobile.tsx, src/components/Header/components/NavbarDesktop.tsx, src/config/globalHeaderData.tsx
This PR extends the existing "redirect after login" functionality to return back to the page the user pressed "Login" from; it effectively will only be useful for pages without authentication (e.g. Data Model Navigator).
N/A
https://tracker.nci.nih.gov/browse/CRDCDH-621
=> CRDCDH-621 Restore current URL on login

src/content/users/APITokenDialog.tsx, src/content/users/UploaderToolDialog.tsx
This PR addresses MUI v4 packaged with Data Model Navigator overriding the dialog styling provided by MUI v5. Visit the DMN page on DEV2 and open either the API Token Dialog or the Uploader CLI Dialog to observe the issue.
> **NOTE**: This is similar to the fix applied in #215 
- Add (a lot) of `!important` CSS styling flags
N/A
=> fix: DMN overriding dialog styling

src/content/dataSubmissions/DataSubmission.tsx
This PR aims to display a "-" for the Upload Type column in the batch table when the Batch Type is "file". Currently, you can only upload a "file" Batch Type by using CLI.
N/A
[CRDCDH-623](https://tracker.nci.nih.gov/browse/CRDCDH-623)
=> CRDCDH-623 Upload Type for file Batch Type

nginx/README.md, nginx/nginx.conf, src/client.ts, src/components/Contexts/AuthContext.test.tsx, src/components/Contexts/AuthContext.tsx, src/components/Contexts/OrganizationListContext.tsx, src/content/dataSubmissions/DataSubmissionsListView.tsx, src/content/organizations/OrganizationView.tsx, src/content/users/APITokenDialog.tsx, src/content/users/ListView.tsx, src/content/users/ProfileView.tsx
This PR updates our authorization implementation to remove the AuthZ service and replace it with the BE.
N/A
CRDCDH-648
=> CRDCDH-648 Replace AuthZ with core BE service

package-lock.json, package.json, src/components/DataSubmissions/RadioInput.tsx, src/components/Footer/FooterDesktop.tsx, src/components/Footer/FooterMobile.tsx, src/components/Footer/FooterTablet.tsx, src/components/Header/HeaderDesktop.tsx, src/components/Header/HeaderTabletAndMobile.tsx, src/components/Header/USABanner.tsx, src/components/Header/components/LogoDesktop.tsx, src/components/Header/components/LogoMobile.tsx, src/components/Header/components/LogoTablet.tsx, src/components/Header/components/NavbarDesktop.tsx, src/components/InactivityDialog/InactivityDialog.tsx, src/components/Questionnaire/FormContainer.tsx, src/components/Questionnaire/RadioYesNoInput.tsx, src/components/Questionnaire/ReviewDataListingProperty.tsx, src/components/Questionnaire/ReviewFileTypeTable.tsx, src/components/Questionnaire/SwitchInput.tsx, src/components/Questionnaire/TableFileTypeAndExtensionInput.tsx, src/components/Questionnaire/TableTextInput.tsx, src/components/Questionnaire/TextInput.tsx, src/content/index.tsx, src/content/questionnaire/FormView.tsx, src/content/questionnaire/sections/D.tsx
This PR aims to remove `@mui/styles` and `styled-components` dependencies from the project. Also, to remove the `--legacy-peer-deps` flag from our node commands.
- Remove all withStyles and replace with MUI styled
- Remove all styled-components references and replace with MUI styled
**NOTE:** This affects Submission Request as well as header/footer. Will need to test carefully before merging.
N/A
=> Remove old styling dependencies 

src/content/questionnaire/FormView.tsx
This PR fixes the "Request Additional Changes" button not taking the width it needs.
Old:
New:
CRDCDH-664
=> CRDCDH-664 fix: Inquire button text wrap

src/content/modelNavigator/hooks/useBuildReduxStore.ts
This PR resets the Model Navigator search history any time the redux store is repopulated. A future solution would be to isolate the model's search history and not clear it automatically, but that will require DMN core updates.
- Dispatch the redux event `SEARCH_CLEAR_HISTORY` when populating the model redux store
CRDCDH-667
=> CRDCDH-667 Clear history when populating model

src/components/DataSubmissions/DataSubmissionUpload.tsx
This PR aims to add loading text "Uploading..." during an upload instead of a loading button icon. The rest of the behavior remains the same
- Updated text while updating to "Uploading..."
- Updated button styling to match M3
[CRDCDH-669](https://tracker.nci.nih.gov/browse/CRDCDH-669)
=> CRDCDH-669 Submission uploading text

src/components/DataSubmissions/ValidationControls.tsx, src/components/GenericAlert/index.tsx, src/content/dataSubmissions/DataSubmission.tsx, src/graphql/getSubmission.ts, src/types/Submissions.d.ts
This PR introduces data submission polling to track the file validation status. 
> [!TIP]
> The validation API works, but no validation happens yet; thus you will need to manually update the data submission object to change `metadataValidationStatus` (sp.) or `fileValidationStatus` (sp) from "Validating" to another state in order to see the button re-enable.
- Removed the usage of states for the Data Submission and Stats so that we can use native Apollo polling directly
- Migrated from `useLazyQuery` to `useQuery` for `GET_SUBMISSION` query
- This will auto fetch the submission on component mount so that we don't need to manually initiate it
- Fixed a 508 issue with an empty button when there are no batch errors
- Fixed GenericAlert hiding under the Navbar Dropdown container (had equal …
=> CRDCDH-659 Poll for file validation status

src/components/DataSubmissions/DataSubmissionUpload.tsx, src/content/dataSubmissions/DataSubmission.tsx
This PR aims to add the "Delete" upload type option to be able to delete previously submitted data.
- Upload process is the same, except with delete as metadataIntention
- Open dialog when trying to upload
- Show banner message that successfully deleted or failed
- Add record to listBatches table (error is async and might require some refreshes)
[CRDCDH-652](https://tracker.nci.nih.gov/browse/CRDCDH-652)
=> CRDCDH-652 Data Submission Delete Upload Type

src/components/DataSubmissions/DataSubmissionUpload.tsx, src/content/dataSubmissions/DeleteDialog.tsx
This PR aims to update the "Delete Data" dialog design when using the "Delete" upload type.
- Created DeleteDialog to match new design
- Delete logic remains the same
[CRDCDH-652](https://tracker.nci.nih.gov/browse/CRDCDH-652)
=> Created custom DeleteDialog to match new design

src/components/Organizations/ConfirmDialog.tsx, src/content/organizations/OrganizationView.tsx, src/graphql/getOrganization.ts
This PR adds a confirmation dialog when an Admin attempts to remove a study currently tied to an active data submission.
- Implement confirmation dialog based on API Token / Uploader CLI dialog (per K.C. request)
- Modify getOrganization query to also fetch current data submissions tied to an org
- NOTE: `getOrganization` is only used by this page. If we ever use it elsewhere, we will need to refactor it to not ALWAYS include the data submissions
CRDCDH-689
=> CRDCDH-689 Warn on removal of study with active data submission

src/components/DataSubmissions/GenericTable.tsx, src/content/dataSubmissions/FileListDialog.tsx, src/types/Submissions.d.ts
This PR slightly modifies the FE implementation of the Batch File List by changing the table's no-content message to conform to the user story. 
> [!NOTE]
> To test this, use the uploader CLI and upload a set of files twice with the config option `overwrite` set to false. 
> Or you can use the DEV submission `3e568f16-f135-47e2-ba69-87d0f707bc01`
- Update the `UploadResult` type definition to include the `skipped` property
- Add a `numRowsNoContent` prop to the generic table
- Replace the default no-content message with the one from the user story
CRDCDH-668
=> CRDCDH-668 Batch File List "No Content" message update

src/content/organizations/OrganizationView.tsx, src/graphql/editOrganization.ts, src/graphql/getOrganization.ts
This PR fixes an issue with the "Active Data Submission" confirmation dialog appearing any time the organization is saved, even after removing the original study that caused the prompt.
- Migrate successful organization save/create GenericAlert to Notistack
- Update organization state after saving changes
CRDCDH-689
=> fix: Study removal prompt persisting past first save

src/content/dataSubmissions/DataSubmissionsListView.tsx, src/content/dataSubmissions/ErrorDialog.tsx, src/content/dataSubmissions/FileListDialog.tsx
Wording changes and small fixes.
- Fixed `DM Version` typo
- Updated "Node Type" to "Type" in the File List Dialog table
- Added word break to error dialog title as it was causing an overflow
[CRDCDH-676](https://tracker.nci.nih.gov/browse/CRDCDH-676) (Data Model Version)
[CRDCDH-780](https://tracker.nci.nih.gov/browse/CRDCDH-780) (File List Dialog bug)
[CRDCDH-552](https://tracker.nci.nih.gov/browse/CRDCDH-552) (Error Dialog)
=> CRDCDH-676 Wording Changes

src/content/dataSubmissions/DataSubmission.tsx, src/graphql/listBatches.ts, src/types/Submissions.d.ts
This PR updates the `BatchStatus` type to conform to the current definition from CRDCDH-736 and implements listBatch polling if there are any batches in the Uploading state.
- Update TypeScript definition of BatchStatus per CRDCDH-736
- Modify listBatches GraphQL to query for full list of batch statuses
- Poll listBatches until there are no batches uploading, when there are no batches, update the data submission to retrieve latest stats
CRDCDH-754
=> CRDCDH-754 Poll for Batch Status Updates

src/content/dataSubmissions/DataSubmission.tsx, src/types/Submissions.d.ts
This PR updates the FE type definitions for a Batch Type (i.e. `UploadType`) to match the new backend implementation. 
- Update `UploadType` to `metadata` and `data file`
- Replace `NewBatch`.`UploadType` from a `string` to `UploadType`
- Replace `QCResult`.`validationType` definition with `UploadType`
- Reverse logic on the Data Upload > Upload Type column for backwards compatibility (M2 submissions will still use `file` and will cause a bug in PROD)
CRDCDH-786
=> CRDCDH-786 Change `file` batch type to `data file`

src/content/dataSubmissions/DataSubmissionActions.tsx, src/graphql/submissionAction.ts
This PR builds off CRDCDH-728 by requiring a comment when performing an administrative submit of a Data Submission.
- Add a Admin Submit dialog that's enabled only when the Submit Button label is "Admin Submit"
- Clear review comment text anytime the dialog is closed (cancel or submit actions)
- Update CRDCDH-728 for latest requirements (comment placeholder)
CRDCDH-715
CRDCDH-728
=> CRDCDH-715 Admin Submit justification, CRDCDH-728 Updates

src/components/DataSubmissions/DataSubmissionUpload.tsx, src/components/DataSubmissions/FlowWrapper.tsx, src/components/DataSubmissions/RadioInput.tsx, src/components/DataSubmissions/ValidationControls.tsx, src/components/DataSubmissions/ValidationStatistics.tsx, src/content/dataSubmissions/DataSubmission.tsx, src/content/dataSubmissions/DataSubmissionsListView.tsx
This ticket changes the flow of the Data Submission UI to:
1. Statistics
2. Upload Metadata
3. Validation
to accommodate the typical user flow. Additionally, it introduces minor changes to the Data Upload tab and validation stats.
> [!Warning]
> This PR does NOT modify the design of the "Upload" or "Validate" buttons to avoid conflicts with CRDCDH-747
- Reorganize Data Submission page (see above)
- Rename Data Upload to Data Activity
- Add placeholder to submission stats when there are no stats yet
- Rename a variable typo `uploadMetatadataInputRef` to `uploadMetadataInputRef`
CRDCDH-765
=> CRDCDH-765 Data Submissions UI Improvements

src/components/DataSubmissions/DataSubmissionUpload.tsx, src/content/dataSubmissions/DataSubmission.tsx
Disable Upload/Delete Upload Type options when no data has been successfully uploaded. 
- If metadataValidationStatus is null and fileValidationStatus is null, then disable options.
[CRDCDH-788](https://tracker.nci.nih.gov/browse/CRDCDH-788)
=> CRDCDH-788 Disable Upload/Delete upload types when no data uploaded successfully

src/content/dataSubmissions/DataSubmission.tsx, src/content/dataSubmissions/QualityControl.tsx
Simple PR to address an additional 508 issue with the color contrast of the "Error" or upload "Failed" states on the Data Submissions QC or Data Activity tables.
N/A
CRDCDH-633
=> CRDCDH-633 508 color contrast on Error/Failed statuses

src/content/dataSubmissions/FileListDialog.tsx
Minor bug fix to use a fallback placeholder for files without a node type. This occurs during `Uploading` or sometimes `Failed` Batch states.
- Use `N/A` when there is no nodeType associated with a file
CRDCDH-835
=> CRDCDH-835 Failed batch has no Node Types for files

src/components/DataSubmissions/DataSubmissionSummary.test.tsx, src/components/DataSubmissions/DataSubmissionSummary.tsx, src/components/Shared/HistoryDialog.tsx, src/components/Shared/ReviewCommentsDialog.test.tsx, src/components/Shared/ReviewCommentsDialog.tsx, src/components/StatusBar/StatusBar.test.tsx, src/components/StatusBar/components/HistorySection.tsx, src/components/StatusBar/components/StatusSection.tsx
Added Review Comments button in Data Submission Dashboard. It will only show latest comment for Rejections.
- Added Review Comments button
- Disabled Review Comments button if not comment is available, instead of hiding button
- Only Rejection reviewComments should be displayed, Admin submit reviewComments should never be shown
- Updated spacing and styling in Summary section
- Reused Review Comments dialog from Questionnaire, with some changes and moved to a shared folder
- Updated questionnaire to use new shared component for dialog
- Updated questionnaire tests
- Added tests for Data Submission Summary section and new Review Comments dialog component 
[CRDCDH-678](https://tracker.nci.nih.gov/browse/CRDCDH-678)
=> CRDCDH-678 Data Submission Review Comments

src/content/dataSubmissions/DataSubmission.tsx
This PR removes the logic that prevents refreshing the batch table for any non-Submitter role. The user story CRDCDH-754 was updated to clarify that any role should poll for batch updates.
N/A
CRDCDH-857 (Bug)
CRDCDH-754 (Original ticket)
=> CRDCDH-857 Refresh batches for any role

src/content/users/APITokenDialog.tsx, src/content/users/UploaderToolDialog.tsx
This PR addresses broken aria references on the CLI Uploader Tool and CLI API Token dialogs.
- Override the default random aria-labelledby ID generated by MUI
- Replace h3/h6 headings with h1/body1 respectively (addresses a 508 warning)
- Fix button contrast issue on API Token download dialog
CRDCDH-864
=> CRDCDH-864 Fix broken aria references and contrast issue

src/components/Carousel/index.tsx, src/components/DataSubmissions/ValidationStatistics.tsx
This is a minor change to the CRDCDH-538 implementation to fix an issue noticed in the prod builds. 
<details>
<summary>Issue 1: Inconsistent Node Sorting</summary>
Without React StrictMode, the nodes in the primary chart would appear in the order that the API sent the nodes until you switch the view type.
</details>
<details>
<summary>Issue 2: Partially Visible Nodes</summary>
For small datasets (under 3 nodes), the carousel would partially overlap with the individual node charts and not provide arrows to make them visible. This is fixed now.
Cases:
- 1 Node [f30c5850-2349-4cd0-a4ef-959b8ea34ee5](http://localhost:4010/data-submission/f30c5850-2349-4cd0-a4ef-959b8ea34ee5/data-activity)
- 2 Nodes [45a25d33-86a5-4cf3-bfa2-9a557dbfeb2c](http://localhost:4010/data-submission/45a25d33-86a5-4cf3 …
=> CRDCDH-538 Fix Node Sorting & Partially-Visible Carousel Elements

src/content/dataSubmissions/DataSubmission.tsx
Fixed alignment of tabs not always being flush with the section under it causing the border from the section under it to show. The problem was only visible in certain scenarios such as zoomed in browsers or different screens.
- Updated alignment to flex-end so that it is always flush with the lower section
N/A
=> Data submission tabs alignment Hotfix

package-lock.json
This PR addresses an issue with the `Data Model Navigator` > `All Data Templates (TSV)` > `File Transfer Manifest` download including ICDC-specific columns added:
- `original_file_size`
- `original_md5sum`
- Update DMN to `v1.1.23`
CRDCDH-886
=> CRDCDH-886 ICDC-specific props added to File Tran. Manifest DL

package-lock.json
This PR embeds the data model version in the Data Model Navigator header if the `Version` property is set in the model-desc file.
> [!note]
> The actual styling differs slightly from Figma to the implementation. Namely the font/font-size.
N/A
CRDCDH-855
=> CRDCDH-855 Display Data Model Version in DMN

src/components/Questionnaire/UnsavedChangesDialog.tsx, src/content/questionnaire/FormView.tsx
This PR introduces auto-saving a Submission Request form when navigating away from the current page. It also migrates the `GenericAlert` component to Notistack.
- If there are no form errors, save the submission request on navigate instead of showing an alert
- Migrate FormView usage of GenericAlert to Notistack
- Update verbiage in Unsaved Changes dialog
CRDCDH-826
=> CRDCDH-826 Submission Request Auto Save

src/components/Contexts/AuthContext.test.tsx
This PR aims to fix the random failures of the `should update the localStorage cache when the user is verified` test case for the AuthContext. It appears to be caused by a race condition.
e.g. https://github.com/CBIIT/crdc-datahub-ui/actions/runs/8100132739/job/22137439227
- Wrap the localStorage expectation in a Jest waitFor action which will continue to "re-test" the expect for up to 1 second before failing
N/A
=> fix: Random AuthContext test case failing in CI

src/utils/statisticUtils.test.ts, src/utils/statisticUtils.ts
This PR addresses new sorting requirements introduced in CRDCDH-956 – Sorting charts by the node total in ascending order.
- Rewrite `compareNodeStats` function to account for node total + node name combination
- Add base test cases for `compareNodeStats` and `calculateMaxDomain` functions
CRDCDH-956
=> CRDCDH-956 Sort charts by Node Total

src/content/dataSubmissions/DataSubmission.tsx
Updated Data Submission Dashboard to default to `Data Activity` tab when the tab is missing in the URL. Also displaying workflow buttons on any tab.
- Set default tab to `Data Activity` when tab is undefined
- Updated workflow buttons to display them always, regardless of tab selected
[CRDCDH-951](https://tracker.nci.nih.gov/browse/CRDCDH-951)
**NOTE:** Bug ticket to fix showing workflow buttons on any tab can't be created due to read-only Jira board, but was verbally discussed
=> CRDCDH-951 Set default Data Submission tab when unspecified

.github/workflows/lint.yml, .github/workflows/test.yml, package.json
=> feat: Coveralls CI Integration

src/components/Contexts/AuthContext.test.tsx
Another PR to fix incorrectly written assertion in the AuthContext. This one has never failed in CI but just failed locally. See #309 for the same fix applied to a different case.
- Wrap localStorage accessing in a Jest waitFor stmt
- Remove duplicate expectation 
N/A
=> fix: AuthCtx expectation failing

src/content/dataSubmissions/DataSubmission.tsx, src/content/dataSubmissions/ErrorDialog.tsx, src/utils/dataSubmissionUtils.test.ts, src/utils/dataSubmissionUtils.ts
Updated Data Submission submit logic to disable submit for all users if any Submission level errors exist, such as orphaned data files. 
- Disabled submit always if any submission level errors exist
- Test formatting changes due to passing entire submission to utility
**NOTE:**
- To test:
- Upload a single Data File into a new submission, validate, and try to submit using "Submitter" and "Admin" role. It should remain disabled for both.
- Upload metadata after uploading Data Files, validate, and now you should be able to admin submit or submit normally if both validations are passed.
[CRDCDH-852](https://tracker.nci.nih.gov/browse/CRDCDH-852)
=> CRDCDH-852 Disable Submit for orphaned files

src/graphql/getSubmission.ts, src/types/Submissions.d.ts, src/utils/dataSubmissionUtils.test.ts
Updated the getSubmission query, types, and unit tests to sync up with BE.
N/A
[CRDCDH-852](https://tracker.nci.nih.gov/browse/CRDCDH-852)
=> CRDCDH-852 Submission File Errors Schema Update

package-lock.json
This PR upgrades our Data Model Navigator version which includes updated parsing of boolean values for Data Model Properties `Req` property.
See updated code here – https://github.com/CBIIT/Data-Model-Navigator/commit/7b98d69a5edf3f36b56a75ea86a1fba596f262e2
<details><summary>Before & After</summary>
<p>
Before:
After:
</p>
</details> 
<details><summary>Testing Change</summary>
<p>
1. Run the branch
2. Go to Data Model Navigator
3. CDS Model
4. Click on the Table View tab
5. Scroll to the bottom and find Data File > Image
6. Look at the "license" property
</p>
</details> 
- Update Model Navigator dependency
CRDCDH-960
=> CRDCDH-960 Fix boolean value parsing of `Req` property

package-lock.json
Minor MVP-2 M3 fix for Data Model Navigator. The search result container was overriding the default `ul` component and using a `div` instead, making it a invalid DOM structure
- https://github.com/CBIIT/Data-Model-Navigator/commit/142be38dd19c5304232cc6105e4b88d54ca90a01
CRDCDH-973
=> CRDCDH-973 Fix Model Navigator `<li>` must be in a `<ul>` or `<ol>`

package-lock.json
Minor Data Model Navigator bug fix to respect the whitespace defined in node property "Acceptable Values". This issue is present in `Table View` > `Data File` > `Image` > `license` property
Before:
After:
- See DMN commit https://github.com/CBIIT/Data-Model-Navigator/commit/d692c5cf99b48ec25a44facd31a78dbf078d2800
N/A
=> CRDCDH-999 Fix collapsed whitespace in Model Navigator value list

src/content/dataSubmissions/DataSubmission.tsx, src/content/dataSubmissions/QualityControl.tsx
MVP-2.1.0 PR to auto refresh the Validation Results table upon starting or finishing the validation process. Also includes a bug fix for the Validation button itself, where it would never change from "Validating..." if the metadata/file validation status remained the same.
e.g. You validate one time and `metadataValidationStatus` is `Error`. You validate again, without uploading anything new, the status quickly becomes `Error` again and the button never sees any change from `Error` -> `Validating` -> `Error` so it just stays `Validating`
- Force immediate Data Submission refetch on validate (bug)
- Refresh QC Results table any time the validation properties update (linked ticket)
CRDCDH-974
=> CRDCDH-974 Auto refresh Validation Results table on validate complete

package-lock.json, package.json, src/types/ProgramConfig.d.ts, src/types/Submissions.d.ts, tsconfig.json
This PR is tangentially related to #262 and enables checking of library (d.ts) files in TypeScript. Enabling this check identified the following issues in our definitions:
> Error: src/types/Application.d.ts(133,6): error TS2300: Duplicate identifier 'FileInfo'.
> Error: src/types/ProgramConfig.d.ts(2,24): error TS1247: A type literal property cannot have an initializer.
> Error: src/types/Submissions.d.ts(59,6): error TS2300: Duplicate identifier 'FileInfo'.
> Error: src/types/Submissions.d.ts(171,6): error TS2300: Duplicate identifier 'ParentNode'.
This change will also enable us to identify any future unresolved types or invalid syntax. e.g.
- Upgrade TypeScript to v5.4.3 – This should have no breaking changes for us ([source](https://github.com/microsoft/TypeScript/wiki/API-Breaking-Ch …
=> DX: Enable TypeScript Lib Check (d.ts) Files

src/content/questionnaire/sections/D.tsx, src/content/questionnaire/sections/Review.tsx
Updated the Clinical Data Types in the Submission Request form. 
- Updated Section D to require at least one Clinical Data Type if the "Clinical" toggle is set to "Yes" in the "Data Types" section.
- Show an error message if no clinical data type is selected and the section is visible
- Show/Hide the Clinical Data Types section in the Review page depending on if "Clinical" toggle is on or off
[CRDCDH-993](https://tracker.nci.nih.gov/browse/CRDCDH-993)
[CRDCDH-994](https://tracker.nci.nih.gov/browse/CRDCDH-994)
=> CRDCDH-993 Submission Request V2 Updating clinical data types 

src/components/DataSubmissions/ValidationControls.tsx
Resolves a MVP-2.1.0 bug where the Data Submission validation controls `canValidateMetadata` and `canValidateFiles` is missing the Data Submission `status` property from the memo hook. This causes the validate button to not become disabled on submit.
- Add Data Submission Status to memoed `canValidateXXX` variable
CRDCDH-1016
=> CRDCDH-1016 Validation Controls memo missing dependency

src/components/DataSubmissions/ValidationControls.tsx
When `validateSubmission` API was called, it was not properly catching the errors, therefore was not showing error message and enabling the validation button after failing.
- Added a catch for API errors
[CRDCDH-1039](https://tracker.nci.nih.gov/browse/CRDCDH-1039)
=> CRDCDH-1039 Show error when validation API call fails

src/components/DataSubmissions/ValidationControls.tsx
The `validationType` was showing as null resulting in validation never happening. Memoization was missing dependency.
N/A
N/A
=> Hotfix: Fixed validate button missing dep

src/components/DataSubmissions/ValidationControls.tsx
Added additional `uploadType` and `dataSubmission` to deps of the memoized validate button. Please double check that I didn't miss any additional missing deps.
N/A
N/A
=> Hotfix: Added uploadType and dataSubmission to deps array for validate button

src/content/dataSubmissions/CreateDataSubmissionDialog.tsx
This is a PR to restore the original spacing between the radio inputs on the "Create Data Submission" dialog, which was messed up by #340 – See below
<details><summary>Previous (bad)</summary>
<p>
</p>
</details> 
<details><summary>Restored (correct)</summary>
<p>
</p>
</details> 
Also remove the MUI loading indicator that appears when the create submission dialog is open, which shouldn't be implemented. See below
<details><summary>Before</summary>
<p>
</p>
</details> 
<details><summary>After</summary>
<p>
</p>
</details> 
- Override Data Submission RadioInput styling for the create submission dialog
- Remove dynamic loading attribute from "Create a Data Submission" button
N/A
=> Restore Create a Data Submission Intention spacing

package-lock.json, src/config/DataCommons.ts, src/types/DataModelNavigator.d.ts
Upgrades Model Navigator to 1.1.30 which adds a new configuration option for specifying the File Transfer Manifest filename. Per request, this is used in:
- Single template TSV for the "File" node
- All template TSV zip package
- Update Model Navigator (See https://github.com/CBIIT/Data-Model-Navigator/compare/dd58d548ec49043636989ff76b21852d41b9396c..747af34f379e272b0077b254a1d0d04ab4a6d527)
- Update type definition for the model navigator config object
CRDCDH-1083
=> CRDCDH-1083 Model Navigator `File` node missing name

src/content/dataSubmissions/DataSubmissionsListView.tsx
Updated the validation for the "Submission Name" input field to trim the whitespace first.
> [!Note]
> This will require a different implementation in `3.0.0` branch since it was refactored and updated to use `react-hook-form`.
> PMVP fix implemented in #355 
[CRDCDH-1080](https://tracker.nci.nih.gov/browse/CRDCDH-1080)
=> CRDCDH-1080 Updated Submission Name input validation to trim whitespace

src/content/dataSubmissions/CreateDataSubmissionDialog.tsx
This PR fixes an issue with creating a submission, where the createSubmission API is never called. 
To verify:
- Fill out the form WITHOUT causing any validation issues
- it should now send the API request
I wasn't able to replicate this when originally testing #355, so it's possible there's an issue beyond this – But this solution is working locally.
- Return `null` from the `validateEmpty` function if there's no issue
N/A
=> fix: Submission Name validation not allowing submit

src/graphql/getSubmission.ts
Cleans up an unused query added (but not needed) for CRDCDH-882.
- Remove QC Result count fetching from within the getSubmission query
N/A
=> Remove unused selection from query

src/components/Questionnaire/Repository.tsx, src/components/Questionnaire/ReviewDataListingProperty.tsx, src/content/questionnaire/sections/C.tsx, src/content/questionnaire/sections/D.tsx, src/content/questionnaire/sections/Review.tsx
This PR modifies the default value delimiter for properties on the Submission Request Review Page and adds a contextual tooltip to indicate the expected delimiter.
- Add `delimiter` prop to ReviewDataListingProperty
- Remove the delimiter when displaying the value line-by-line (e.g. no longer include the `,` at the end of the value)
- Override default comma (`,`) delimiter for the fields:
- B: Repository > Other Data Types (free text)
- C: Other Cancer Types (free text)
- C: Pre-Cancer Types (free text)
- C: Other Specie(s) Involved (free text)
- D: Other Clinical Data Types (free text)
- D: Other Data Types (free text)
- Add tooltips for the above fields to indicate that a pipe (`|`) should be used to separate values
CRDCDH-1114
=> CRDCDH-1114 Submission Request Free-text Delimiter

src/components/DataSubmissions/ValidationControls.tsx, src/utils/dataValidationUtils.ts
This PR covers a missing requirement that Data Curators or Admins should be able to validate a Submitted data submission. These changes should only effect Data Curators and Admins for a Data Submission in the "Submitted" state – Nothing else should change...
> [!NOTE]
> When migrating to v3.0.0, I have test coverage for these changes written already, I just need to migrate them.
- Rewrite the validate permission map to be a simplified object.
- `Key`: Submission Status
- `Value`: List of Roles that can validate
- Create a util to determine what the default Validation Target should be, we had one for the Validation Type already
- Disable "New" validation target if the submission is Submitted
- This is already disabled in statuses beyond "Submitted"
CRDCDH-1137
=> CRDCDH-1137 Allow validation in Submitted state

src/components/DataSubmissions/BackButton.tsx, src/components/DataSubmissions/DataSubmissionSummary.tsx, src/components/DataSubmissions/DataSubmissionUpload.tsx, src/components/DataSubmissions/LinkTab.tsx, src/components/DataSubmissions/ValidationControls.tsx, src/content/dataSubmissions/DataSubmission.tsx, src/content/dataSubmissions/DataSubmissionActions.tsx, src/content/dataSubmissions/ErrorDialog.tsx, src/content/dataSubmissions/FileListDialog.tsx, src/content/dataSubmissions/QualityControl.tsx
Reduced the getSubmission and listBatches polling from 60s to 1s intervals. Also fixed race-condition bug involving Validate button and polling.
- Added polling for listBatches API
- Set polling interval for getSubmission and listBatches to 1s
- Memoized Data Submission components as the frequent 1s polling would cause excessive re-renders. 
- Fixed bug where clicking the validate button would set the button text to "Validating..." and would infinitely poll getSubmission even though it is done validating.
This was due to a race condition where if the `metadataValidationStatus` is set to "Error" and when an additional validate is started with no changes it would poll getSubmission, but receive the same data back with `metadataValidationStatus` still as "Error". Receiving the same data back …
=> CRDCDH-1138 Reduce Data Submission polling from 60s to 1s

src/components/DataSubmissions/ValidationControls.tsx
This PR fixes a hardcoded validation target of "New", which is incorrect for Admins/Curators for a Submitted submission.
N/A
CRDCDH-1162
=> CRDCDH-1162 Fix hardcoded validation target

src/components/DataSubmissions/DataUpload.test.tsx, src/components/DataSubmissions/DataUpload.tsx, src/components/DataSubmissions/ValidationControls.test.tsx, src/components/DataSubmissions/ValidationControls.tsx, src/utils/dataSubmissionUtils.test.ts, src/utils/dataSubmissionUtils.ts
Updated Step 2 in the Data Submission data upload process to display text when Submission is "Metadata Only".
- Replaced Step 2 text and hid buttons when Submission is "Metadata Only"
- Disabled "Validate Data Files" and "Both" when Submission is "Metadata Only". Although, this would never be enabled anyways since BE is blocking Data Files from ever being uploaded for this `dataType`.
- The "Submit" button is enabled when all metadata passed validation in a "Metadata Only" dataType Submission.
> [!NOTE]
> BE API's are not ready. Submit won't work, but the button will be enabled. Also, you can still upload Data Files to a 'Metadata Only' Submission via the CLI.
[CRDCDH-1095](https://tracker.nci.nih.gov/browse/CRDCDH-1095)
=> CRDCDH-1095 Data Submission Upload update for "Metadata Only" Data Type

src/components/DataSubmissions/MetadataUpload.test.tsx, src/components/DataSubmissions/MetadataUpload.tsx, src/content/dataSubmissions/DataSubmission.tsx, src/content/dataSubmissions/SubmittedData.tsx
This PR adds memoization to the Submitted Data tab, which was created after memoizing other data submission components.
> [!NOTE]
> You can observe the rerendering by hovering over the Export TSV icon, which collapses and reopens every rerender
https://github.com/CBIIT/crdc-datahub-ui/assets/38357871/97157b0c-15e1-4392-b34b-ea7ce283eaaa
- Memoize the SubmittedData component to prevent rerendering when polling getSubmission
- Fix the import of MetadataUpload, the default export was memoized but the Data Submission page was using the const export
N/A
=> Fix Data Submission > Submitted Data Memoization

package-lock.json
This PR upgrades DMN to `v1.1.31` which adds support for `list` model property types.
**List WITHOUT acceptable values defined (before/after):**
Table View > Study > Study > `data_types`
**List WITH acceptable values defined (before/after)**
Table View > Data File > File > `experimental_strategy_and_data_subtypes`
- See DMN changes in commit https://github.com/CBIIT/Data-Model-Navigator/commit/8612cce7e56a0d6d0368656543db92dda29cafe6
CRDCDH-1187
=> CRDCDH-1187 Parse Model Property `list` Type

package-lock.json, package.json, src/setupTests.tsx
This PR prevents console.warn and console.error calls from silently happening in tests and not failing the Jest action for it.
- Add `jest-fail-on-console` dependency
N/A
=> Fix silent warnings allowing Jest to succeed

src/components/DataSubmissions/DataUpload.test.tsx
This PR should fix a randomized test failure caused by React Hook Form. See the action run [9411823501](https://github.com/CBIIT/crdc-datahub-ui/actions/runs/9411823501) or [9418434115](https://github.com/CBIIT/crdc-datahub-ui/actions/runs/9418434115).
I can't replicate this issue locally, but I did re-run the Jest job against this PR 5 times without issues:
- [258](https://github.com/CBIIT/crdc-datahub-ui/actions/runs/9418412154)
- [257](https://github.com/CBIIT/crdc-datahub-ui/actions/runs/9418410980)
- [256](https://github.com/CBIIT/crdc-datahub-ui/actions/runs/9418408396)
- [255](https://github.com/CBIIT/crdc-datahub-ui/actions/runs/9418286250)
- [254](https://github.com/CBIIT/crdc-datahub-ui/actions/runs/9418201981)
- Wrap a test case in `act` and disable linting against it
N/A
=> fix: Random failures with Jest CI

src/content/dataSubmissions/DataSubmissionActions.tsx
Updated Data Submission Dashboard to display "Submit" and "Cancel" buttons when the submission is in a "Rejected" status.
- Added transition in Data Submission workflow "Rejected" => "Submitted"
- Added transition in Data Submission workflow "Rejected" => "Canceled"
> [!NOTE]
> BE doesn't yet support transition from "Rejected" => "Canceled".
[CRDCDH-1170](https://tracker.nci.nih.gov/browse/CRDCDH-1170)
=> CRDCDH-1170 Added Submit and Cancel buttons when Data Submission is in Rejected status

src/content/dataSubmissions/DataSubmissionActions.tsx
Updated the dialog text for the Submit action, when the submission status is currently in "Rejected" status. The submitter will be resubmitting without any changes.
N/A
[CRDCDH-1170](https://tracker.nci.nih.gov/browse/CRDCDH-1170)
=> CRDCDH-1170 Update Submit dialog text for resubmissions

src/components/DataSubmissions/DeleteAllOrphanFilesButton.tsx, src/components/DataSubmissions/DeleteOrphanFileChip.tsx, src/content/dataSubmissions/Contexts/QCResultsContext.tsx, src/content/dataSubmissions/QualityControl.tsx
Deprecated deleting orphaned files buttons and removed them from the Validation Results tab. 
- See submission `8b2e93a6-2b78-4a89-81fe-2174d0cb3b42` for testing. It has orphaned files.
> [!NOTE]
> This will be handled a different way in the Data Viewer tab instead.
[CRDCDH-1254](https://tracker.nci.nih.gov/browse/CRDCDH-1254)
=> CRDCDH-1254 Deprecate deleting orphaned files in Validation Results tab

src/content/organizations/OrganizationView.tsx, src/graphql/createOrganization.ts, src/graphql/editOrganization.ts, src/graphql/getOrganization.ts, src/graphql/index.ts, src/graphql/listApprovedStudies.ts, src/graphql/listApprovedStudiesOfMyOrganization.ts, src/types/ApprovedStudies.d.ts, src/types/Auth.d.ts, src/utils/formUtils.test.ts, src/utils/formUtils.ts
This PR finishes CRDCDH-1297 and updates edit/create Organization API to send the studyID instead of the name/abbreviation.
(Requirement 3 – Organization Edit changes)
- Update the Organization.studies type from a subset `{ name, abbreviation }` to the full `ApprovedStudy`
- Provide the ApprovedStudy `_id` when editing/creating organizations instead of `{ name, abbreviation}`
- Move `EditOrganizationInput` global type definition to the GraphQL mutation file instead
- Update `mapOrganizationStudyToId` to handle the situation in which an organization's studies have IDs already
- NOTE: This utility is somewhat redundant but I left it in place for backwards compatibility when an organization doesn't have the full ApprovedStudy object (i.e. it was saved before these API changes)
CRDCDH-1297
=> CRDCDH-1297 Edit/Add organization should use studyID (Pt. 2)

src/components/DataSubmissions/RadioInput.tsx, src/content/dataSubmissions/CreateDataSubmissionDialog.tsx, src/content/dataSubmissions/DataSubmission.tsx, src/content/dataSubmissions/DataSubmissionsListView.tsx, tsconfig.json
Data Submission Dashboard Improvements - Tooltips, Tab Name
- Added fields (`{tooltip: boolean; tooltipContent: string | ReactNode}`) to the option array passed to `RadioInput`.
- These fields will control the conditional render of a tooltip around the radio button and the content of the tooltip.
- https://tracker.nci.nih.gov/browse/CRDCDH-1248
https://github.com/CBIIT/crdc-datahub-ui/assets/158205521/b7684b66-a55d-4c67-b905-72e46c97bb2f
=> CRDCDH-1248: data submission dashboard improvements

src/components/GenericTable/index.test.tsx, src/components/GenericTable/index.tsx, src/content/dataSubmissions/SubmittedData.tsx
This PR changes how a horizontal scrolling table should be implemented. The previous implementation does not work for tables with a small number of columns. No other tables should be effected by this change.
> [!NOTE]
> To support horizontal scrolling for any new tables, simply apply `tableProps={{ sx: { whiteSpace: "nowrap" } }}` to the table
> [!NOTE]
> To test this change, use the ICDC loading file examples and look at the `enrollment` node.
- Remove `horizontalScroll` prop
- Add a wrapper around the GenericTable Table element and allow width expansion beyond the full width
- Update GenericTable tests for this change
CRDCDH-1318
=> CRDCDH-1318 Fix Data View Table Width

src/components/Contexts/SubmissionContext.test.tsx, src/components/Contexts/SubmissionContext.tsx, src/components/DataSubmissions/CrossValidationButton.test.tsx, src/components/DataSubmissions/ValidationControls.test.tsx, src/content/dataSubmissions/DataActivity.test.tsx, src/content/dataSubmissions/DataActivity.tsx
This PR resolves one of the issues identified in #423; When the SubmissionContext is polling for status changes, it forces almost all of the nested components to rerender, even when there are no changes in the data. This also addresses an issue with the Table Tooltips reopening constantly on hover when polling. 
Before (rerenders highlighted):
https://github.com/user-attachments/assets/d5a161eb-35f0-436e-a7ce-0eca9df64d6f
After (rerenders highlighted):
https://github.com/user-attachments/assets/e34b9e38-a48c-4786-8e89-6a8ea7fae0f0
- Memoize the submission context state
- Memoize the SubmissionContext Provider
- Remove `isPolling` from the context state and use `status` of `POLLING` instead
N/A
=> fix: Heavy rerendering caused by SubmissionContext polling

src/content/dataSubmissions/DataSubmission.tsx, src/content/dataSubmissions/QualityControl.test.tsx, src/content/dataSubmissions/QualityControl.tsx
This PR introduces minor changes to the QC table no-content message and also adds test coverage to the component.
- Update the QC table placeholder
- Memoize the QC table AdditionalActions
- Migrate deprecated submission data prop drilling to the submission context
- Add basic test coverage for the QC tab (mostly based off of the Cross Validation's cases)
CRDCDH-1409
=> CRDCDH-1409 Update QC Table Placeholder

src/types/Submissions.d.ts, src/utils/dataSubmissionUtils.test.ts, src/utils/dataSubmissionUtils.ts
Added consideration for "Rejected" and "Withdrawn" statuses belonging to other submissions within the same study. This will display a custom alert message (same one "In Progress" was already using) when a Data Curator/Admin clicks the Release button and gets a dialog popup. 
- Updated `shouldDisableRelease` utility function logic to include "Rejected" and "Withdrawn" when checking whether or not to require an alert
- Updated tests for the utility function
- Updated types
> [!NOTE]
> Should be merged after BE PR is merged. https://github.com/CBIIT/crdc-datahub-backend/pull/411
[CRDCDH-1489](https://tracker.nci.nih.gov/browse/CRDCDH-1489)
=> CRDCDH-1489 Cross Submission Validation Updates

src/components/DataSubmissions/CreateDataSubmissionDialog.tsx
Updated create submission field to validate empty value when dbGaPID is required. Previously you could enter empty spaces to bypass required field.
N/A
> [!NOTE]
> This is separate from BE implementation, but related. Can be merged independently from each other.  
[CRDCDH-1545](https://tracker.nci.nih.gov/browse/CRDCDH-1545)
=> CRDCDH-1545 Create Submission validate dbGaPID for controlled access study

src/config/AuthRoles.ts, src/types/Auth.d.ts
This PR extends CRDCDH-1444 to allow the "Federal Monitor" role to access the Operation Dashboard. 
> [!NOTE]
> This role cannot actually be assigned ATM but this can be merged regardless.
- Remove comments relating to MVP-1 roles that will not be added
- Update Auth Role type definitions to support `Federal Monitor`
- Update DashboardRoles to add `Federal Monitor`
CRDCDH-1496 (FE Task)
CRDCDH-1474 (User Story)
=> CRDCDH-1496 Add `Federal Monitor` to Operation Dashboard

src/components/DataSubmissions/RelatedNodes.tsx
Fix issue where not all related nodes are displayed in the tabs. Added ability to scroll through tabs using arrows on either side of the tabs. Arrows only visible if there's more nodes to scroll through.
N/A
> [!Note]
> I used the following submission for testing on DEV2. `3f8fe675-14f7-4074-b86c-9cc01e95c002` Although, the submission is not mine, so it shouldn't be modified. See node type "case" for the scrollable tabs.
[CRDCDH-1594](https://tracker.nci.nih.gov/browse/CRDCDH-1594)
=> CRDCDH-1594 Add scrollable tabs for Related Nodes dialog

src/components/DataSubmissions/CrossValidationFilters.test.tsx, src/components/DataSubmissions/CrossValidationFilters.tsx, src/components/DataSubmissions/SubmittedDataFilters.test.tsx, src/components/DataSubmissions/SubmittedDataFilters.tsx, src/content/dataSubmissions/CrossValidation.test.tsx, src/content/dataSubmissions/QualityControl.test.tsx, src/content/dataSubmissions/QualityControl.tsx, src/content/dataSubmissions/SubmittedData.test.tsx, src/graphql/index.ts, src/graphql/submissionStats.ts
This PR standardizes the sorting of the Node Type filter across different tabs on the Data Submission page.
- Define the input type definition for the SUBMISSION_STATS query and reference it in the implementations
- Cross Validation > Replace the usage of LIST_NODE_TYPES with SUBMISSION_STATS so we can sort the node order
- Data View and Validation Results > Remove the sorting reversal of the node types array
- Miscellaneous updates to test coverage related to these changes
CRDCDH-1605 (Task)
CRDCDH-1562 (Story)
=> CRDCDH-1605 Standardize Node Type filter sorting

src/components/DataSubmissions/DataUpload.test.tsx, src/components/DataSubmissions/DataUpload.tsx, src/components/UploaderConfigDialog/index.test.tsx, src/components/UploaderConfigDialog/index.tsx
This PR modifies the CLI Configuration download dialog to make fields required and update the verbiage to indicate S3 buckets are now supported.
- Update the CLI Config form to make the data file folder path and file manifest path fields required
- Update the CLI Config dialog to memoize it
- Standardize the dataType logic in the DataUpload component
- Update test coverage for the misc. changes
CRDCDH-1614 (Task)
CRDCDH-1565 (User Story)
=> CRDCDH-1614 Misc. CLI Config File dialog updates

src/config/AuthRoles.ts, src/content/users/ProfileView.tsx, src/hooks/useProfileFields.test.ts, src/hooks/useProfileFields.ts
This PR updates the Data Curator implementation to add Data Commons assignment, identical to Data Commons POC functionality.
> [!NOTE]
> This feature is still waiting for BE updates including:
> - Allow assignment of Data Commons to a Curator
> - Update the on save error message when a DC is not assigned
>
> But the PR can be merged without these changes.
- Require Data Commons for Data Curators
- Hide Organization field for Data Curators 
- Update ProfileView to support a hidden Organization field (previously wasn't necessary)
- Update misc. test coverage for these changes 
CRDCDH-1632 (FE Task)
CRDCDH-1567 (User Story)
=> CRDCDH-1632 Data Curator Data Commons assignment

src/components/GenericTable/index.tsx, src/components/TruncatedText/index.test.tsx, src/components/TruncatedText/index.tsx, src/content/dataSubmissions/DataSubmissionsListView.tsx, src/content/organizations/ListView.tsx, src/content/questionnaire/ListView.tsx, src/content/users/ListView.tsx
Updated Data Submission List table to prevent text wrapping in the table rows.
- Reduced font size of all tables by 2px (16px => 14px)
- Reduced the start and end padding of all tables (40.44px => 24px)
- Set fixed-widths to specific columns in the Data Submission List table
- Forced text truncation for variable-width columns in the Data Submission List table. When truncated the text is hoverable and a tooltip will appear with full text
- Allowed wrapping in header names as this saves extra space
- If "Submission Name" columns is truncated, I left the original solid underline instead of changing it to a dashed underline to avoid confusion. Deleted/Archived submission do have the dashed underline as they are not clickable
- Moved "dbGaP ID" column to variable-length columns as it allows up …
=> CRDCDH-1607 Data Submission List table improvements

src/content/organizations/OrganizationView.tsx, src/content/users/ProfileView.tsx, src/graphql/index.ts, src/graphql/listApprovedStudies.ts, src/graphql/listApprovedStudiesOfMyOrganization.ts, src/types/ApprovedStudies.d.ts, src/types/Submissions.d.ts, src/utils/formUtils.test.ts
The API was updated to support more functionality and params, but caused breaking changes to existing usage of this query. This PR is just to fix the existing usage.
- Updated `listApprovedStudies` query and `ApprovedStudy` type
- Updated return type for `ApprovedStudyOfMyOrganization` query
- Updated Profile page and Org view page to return all studies
- Fixed broken tests
[CRDCDH-1500](https://tracker.nci.nih.gov/browse/CRDCDH-1500) (Related, but not the implementation)
=> Hotfix: Fix Approved Studies queries and usage

.github/workflows/lint.yml, .github/workflows/test.yml, .github/workflows/typescript.yml
A QoL update to resolve GitHub Actions warnings related to relying on dependencies that use Node v16.
=> fix: Upgrade outdated action dependencies

src/components/Contexts/SubmissionContext.test.tsx, src/components/DataSubmissions/CrossValidationButton.test.tsx, src/components/DataSubmissions/CrossValidationFilters.test.tsx, src/components/DataSubmissions/DataUpload.test.tsx, src/components/DataSubmissions/DeleteAllOrphanFilesButton.test.tsx, src/components/DataSubmissions/DeleteNodeDataButton.test.tsx, src/components/DataSubmissions/DeleteOrphanFileChip.test.tsx, src/components/DataSubmissions/ExportCrossValidationButton.test.tsx, src/components/DataSubmissions/ExportValidationButton.test.tsx, src/components/DataSubmissions/MetadataUpload.test.tsx, src/components/DataSubmissions/ValidationControls.test.tsx, src/components/DataSubmissions/ValidationStatistics.test.tsx, src/components/DataSubmissions/ValidationStatus.test.tsx, src/content/dataSubmissions/CrossValidation.test.tsx, src/content/dataSubmissions/DataActivity.test.tsx, src/content/dataSubmissions/DataSubmissionsListView.tsx, src/content/dataSubmissions/QualityControl.test.tsx, src/graphql/getSubmission.ts, src/graphql/listSubmissions.ts, src/types/Submissions.d.ts, src/utils/dataSubmissionUtils.test.ts
Added `nodeCount` column to Data Submission List table and formatted the value.
- Update the Submission type to include nodeCount
- Added `nodeCount` to listSubmissions query return
- Added `nodeCount` to getSubmission query return
- Updated tests to include new property in base submission
- Added new column in Data Submission List table to include `nodeCount`, also reduce spacing between cells to make room for it to avoid horizontal scrolling
> [!NOTE]
> The BE to support including `nodeCount` in the listSubmissions query is not ready yet. I can't test additional ticket requirements until this is ready (Such as sorting and making sure it is still visible for specific submission statuses), but no further FE changes should be required. …
=> CRDCDH-1606 Add nodeCount column to Data Submission List table

src/components/Questionnaire/CustomAutocomplete.tsx, src/content/questionnaire/sections/C.tsx
This PR migrates the existing Submission Request > Section C > Cancer Types dropdown to an autocomplete component, maintaining the multi-select functionality.
> [!NOTE]
> This migration is backwards-compatible with the previous implementation in 3.0.0.
- Build out a MUI Autocomplete wrapper which overwrites the native multi-select "tagging" functionality
- We already have a autocomplete input for the form, but it's tightly constrained to the expected functionality of a "free-solo" (aka, any value is acceptable) autocomplete. I decided to create another one because I don't want to impact the existing implementation.
- Minor updates to Section C and how we handled the "Not Applicable" option selection
CRDCDH-1611 (FE Task)
CRDCDH-1191 (User Story)
=> CRDCDH-1611 Submission Request Cancer Types Autocomplete

src/content/questionnaire/sections/Review.tsx
Minor PR to fix a 3.0.0 regression for the Other Clinical Data Types delimiter. This was introduced when merging 2.1.0 into 3.0.0
- Remove the explicit `split` call on the Other Clinical Data Types field in the Review Section. Calling `split` on the field pre-maturely turned it into an array, causing the `|` delimiter to be unused
CRDCDH-1675
=> CRDCDH-1675 Fix Other Clinical Data Types delimiter

.eslintrc.cjs, src/components/DataSubmissions/CreateDataSubmissionDialog.test.tsx, src/components/DataSubmissions/CreateDataSubmissionDialog.tsx, src/content/questionnaire/sections/B.tsx, src/utils/formUtils.test.ts, src/utils/formUtils.ts, tsconfig.json
This PR "fixes" a few places where emojis were implicitly allowed, it also makes some related changes to our TS project config.
- Sync ESLint and TypeScript ECMA version to ES2015 (ES6)
- I bumped the ES version to ES6 since that was required to use a unicode RegEx. The browser support for the FE drops slightly, but it's most likely worth the trade-off
- (Unrelated) remove explicit type injection for TS, and use defaults
- Create a emoji validation utility function that integrates with React Hook Form (also kinda works with the Questionnaire)
- Prevent emojis in:
- Create Data Submission > dbGaPID 
- Create Data Submission > Submission Name
- Submission Request > Section B > Study Name (This was only per Sofia request, but all other fields are completely out of scope of this bug)
- …
=> CRDCDH-1686 Base implementation for Emoji Validation

src/components/DataSubmissions/DataSubmissionListFilters.tsx
Fix the debouncing not working when the organization dropdown is read only. This is due to the form updating with the same organization value every time there's a change.
- Added check to make sure the form doesn't update with the same value for organization
[CRDCDH-1609](https://tracker.nci.nih.gov/browse/CRDCDH-1609) (Task)
[CRDCDH-1412](https://tracker.nci.nih.gov/browse/CRDCDH-1412) (User Story)
=> Hotfix: CRDCDH-1609 Data Submission Filters - Fix form from updating with same value 

src/utils/formUtils.test.ts, src/utils/formUtils.ts
Simple bug fix to address the formatFullStudyName not ignoring casing when comparing the equality of the Study Name and Study Abbreviation.
- Force study name and abbreviation to lowercase before comparing equality
- Update test coverage to test for this bug
CRDCDH-1774
=> CRDCDH-1774 Ignore casing when comparing name/abbr

src/config/SubmitButtonConfig.ts, src/utils/dataSubmissionUtils.test.ts
Removed Admin Override option for when missing either "Metadata" or "Data Files" within a "Metadata and Data Files" Data Submission.
- Removed Admin Override rule
- Updated some basic rules to be required to avoid it being overridable 
- Updated tests to reflect change
[CRDCDH-1674](https://tracker.nci.nih.gov/browse/CRDCDH-1674) (Bug Ticket)
=> CRDCDH-1674 Update Submit button logic for Admin Submit

src/config/DataCommons.ts
This PR adds FE support for the "Test MDF" data common (aka data model).
> [!Warning]
> Model navigator can load this model, but some functionality is broken (especially in the table view).
- Add DMN config for the Test MDF model
CRDCDH-1780 (FE Task)
CRDCDH-1448 (User Story)
=> CRDCDH-1780 Add "Test MDF" data model

src/content/dataSubmissions/DataActivity.tsx, src/graphql/listBatches.ts, src/types/Submissions.d.ts
This PR adds a new "Uploaded By" column to the Data Activity tab which displays who uploaded the batch (The data submission submitter, organization owner, or collaborator).
> [!Warning]
> There are requested changes in the BE to correctly store the name of the batch creator. Currently, it just stores the name of the original submission request creator. Unless the schema field names change, there should be no FE impact.
- Add the "Uploaded By" column to the Data Submission > Data Activity Tab
- Copy the concise date formatting from the Data Submission List and apply it to the Uploaded Date column
- Add `submitterName` and `submitterID` to the Batch type, both of these fields do not exist in prior releases, so I marked them as "optional"
- Refine the `NewBatch` type to inherit from the …
=> CRDCDH-1739 Data Activity show who uploaded

src/config/DataCommons.ts, src/config/HeaderConfig.ts
This PR introduces a fake data model "Hidden Model" so that we can test the hiding functionality on lower tiers without using a real data model. After a DevOps change, this model will be hidden permanently.
> [!Note]
> This model does not have any actual model files defined ATM, so it will not load in model navigator.
- Add a fake data model with bare minimum configuration
- Change the NavBar config to not append "Model" after the DC name if it includes "Model" already (e.g. "Hidden Model Model")
CRDCDH-1826 (FE Task)
=> CRDCDH-1826 Add a fake data model

src/content/studies/ListView.tsx
Added truncated text values in the Manage Studies table to avoid text wrapping. 
- Truncated text and gave tooltips for all columns except for "Access Type", "ORCID", and "Created Date"
- The "dbGaPID" column has a 15 max character limit
- The "Created Date" is the shortened date with a tooltip.
[CRDCDH-1803](https://tracker.nci.nih.gov/browse/CRDCDH-1803)
=> CRDCDH-1803 Truncate text in the Manage Studies table

src/components/HistoryDialog/index.test.tsx, src/components/HistoryDialog/index.tsx, src/components/StatusBar/StatusBar.test.tsx, src/components/StatusBar/components/HistorySection.tsx, src/components/TruncatedText/index.test.tsx, src/components/TruncatedText/index.tsx, src/graphql/getSubmission.ts, src/setupTests.tsx, src/types/Globals.d.ts
This PR introduces a rewrite of the History Dialog's underlying component, which incorporates a design update and an additional field indicating which user performed the history transition.
> [!NOTE]
> This design change impacts the Submission Request too, but the "User" column won't appear there (intentionally) since we don't get `userName` from the getApplication API.
- Rewrite the History Dialog to be slightly more efficient (memoization and optimizing usage of callbacks, etc)
- Rebuild the dialog UX without the MUI timeline (we essentially weren't using anything from it)
- Add support for custom styling on the TruncatedText component
- Minor updates to unit tests that were impacted by changes
- ~~Attempt to resolve transition-based ACT warnings by disabling MUI transitions~~ [Did not …
=> CRDCDH-1740 Redesign History Dialog component

src/components/AdminPortal/Organizations/ConfirmDialog.tsx, src/components/AdminPortal/Organizations/StudyTooltip.test.tsx, src/components/AdminPortal/Organizations/StudyTooltip.tsx, src/components/Organizations/StudyTooltip.tsx, src/content/organizations/ListView.tsx, src/content/organizations/OrganizationView.tsx
This PR primarily addresses the legibility of the Manage Organizations > Study Tooltip by adding bullet points and more separation between the studies in the list.
- Put Study Tooltip content into a unordered list and reduce the content font size
- Minor optimization of study tooltip (memoize the content and also the component)
- Add minimal test coverage for the study tooltip
- Migrate the `Organizations` components folder to the existing `AdminPortal` folder
CRDCDH-1823
=> CRDCDH-1823 Address Study Tooltip Legibility

src/components/DataSubmissions/CrossValidationFilters.test.tsx, src/components/DataSubmissions/CrossValidationFilters.tsx
This PR fixes an issue where "Data File" incorrectly appears in the Node Type filter dropdown for Cross Validation; Since cross validation is never performed against Data Files, this option shouldn't be visible.
> [!NOTE]
> The submission `cca9cf14-14ac-4f3f-8d7f-7e1e18e47f79` can be used for testing, which has Data Files uploaded.
- Filter data files from the nodeTypes dropdown
- Add test coverage for this requirement
CRDCDH-1756
=> CRDCDH-1756 Filter "Data File" from Cross Validation Node Types

package-lock.json, package.json, src/hooks/useBuildReduxStore.ts, src/types/DataCommon.d.ts, src/types/DataModelNavigator.d.ts, src/utils/dataModelUtils.test.ts, src/utils/dataModelUtils.ts
This PR updates DMN to support an arbitrary number of Data Model Files (1 or more) by combining them into one aggregate object. Additionally, I also removed redux logger as CRDC FE doesn't have any purpose for logging the redux store state and it pollutes our console. 
> [!NOTE]
> To test the parsing and combination of the model files:
> 
> 1. Set the env variable `REACT_APP_DEV_TIER="model-with-3-files"`
> 2. That branch contains the "Test MDF" model with [4 separate model files](https://github.com/CBIIT/crdc-datahub-models/tree/model-with-3-files/cache/Test%20MDF/1.0.0) that have overlapping content
> 3. Run the FE and open the "Test MDF" model in DMN
> 4. You should see the various content from different model files aggregated correctly
- Upgrade Data Model Navigator – …
=> CRDCDH-1744 Support arbitrary number of Model Files

package-lock.json
This PR updates the core DMN package to address legibility concerns on the Table View tab and adjust the verbiage of the node/property counter.
> [!Warning]
> This PR is based off of CRDCDH-1744 (#505) since both of them update DMN. 
<details><summary>Node Level Comparison</summary>
<p>
</p>
</details> 
<details><summary>Property Table Comparison</summary>
<p>
NOTE: Only the headers/padding changed here. The table content is already ~16px (equal to the rest).
</p>
</details> 
<details><summary>(Unrelated) Added Padding to Component</summary>
<p>
This is unrelated to the user story, but I added padding to the bottom of the DMN component to address ugly spacing issues.
</p>
</details> 
See comparison here – https://github.com/CBIIT/Data-Model-Navigator/compare/8a2cc78f7c9e3e9061e8ca52f7f0dbf …
=> CRDCDH-1763 Address DMN legibility

package-lock.json
Minor styling fix for the "Assignment: Extended" label extending beyond the border of the pill (ICDC has a lot of this). 
Old (on DEV):
New (in PR):
N/A – See DMN changes https://github.com/CBIIT/Data-Model-Navigator/compare/f750e2f42f8913b7dfc7a8bdf39c98f2513692b4...4b5c21a892c84178088541f9a31717d74f048087
CRDCDH-1763 (Task)
CRDCDH-1758 (User Story)
=> CRDCDH-1763 (v2) Fix Assignment label overlap

src/components/Contexts/SubmissionContext.tsx, src/content/dataSubmissions/DataSubmission.tsx, src/content/operationDashboard/DashboardView.test.tsx, src/content/operationDashboard/DashboardView.tsx
This PR updates the QuickSight implementation to provide contextual information to the dashboard. In particular, it provides the assigned list of Studies or Data Commons assigned to the user, which QuickSight then uses to filter the Data Submission Dashboard content. 
Related to this, I also updated the error handling of the Data Submission page to be consistent with the Submission Request Page, Organization Page, Profile Page, etc by redirecting back to the Data Submission List page.
> [!NOTE]
> The Data Submission page still has 1 inconsistency with most of the other features – There is no full screen loader while fetching the submission data initially. I didn't address this as it may have significant side-effects, but it's something we might want to address eventually. 
- Revamp the …
=> CRDCDH-1882 QuickSight – Role-Based Content Filtering

src/components/ExportRequestButton/pdf/Generate.ts
This PR resolves a bug where Submission Requests with a long study name + abbreviation don't properly wrap in the PDF export and it causes text to be cut off.
- Fine-tune the handling of text-wrapping for the Study Name in the PDF header
CRDCDH-1773
=> CRDCDH-1773 Fix rendering of long Study Names

package-lock.json, src/graphql/retrieveCDEs.ts, src/hooks/useBuildReduxStore.ts, src/types/CDEs.d.ts, src/utils/dataModelUtils.test.ts, src/utils/dataModelUtils.ts
This PR updates the CDE integration to sync the parsing logic. Specifically:
- Empty permissible values array – convert the property to a string
- API does not return anything for a specific CDE (it's not in the API response) – show an error for that CDE
- Search for the `Term` with caDSR origin, instead of just the first one (DH requirement change)
- Always show the CDE Origin from the MDF, even though it will always (in 3.1.0) be "caDSR" or akin
The first two logic updates are highlighted below, everything else in the table was already covered.
<details><summary>Details</summary>
<p>
</p>
</details> 
- Always populate CDE info (even if there's an issue with the PermissibleValues)
- Use the exact "CDE Origin" provided in the MDF for the caDSR CDE Term
- Update logic to match the matrix …
=> Synchronize CDE parsing logic

src/components/DataSubmissions/DataSubmissionListFilters.test.tsx, src/components/DataSubmissions/DataSubmissionListFilters.tsx, src/components/DataSubmissions/SubmissionHeaderProperty.tsx, src/content/dataSubmissions/Controller.tsx, src/content/dataSubmissions/DataSubmissionsListView.tsx, src/graphql/listSubmissions.ts
Update the Organization select dropdown from the Data Submission List table filters so that any user can select from relevant Organizations.
- Updated listSubmissions API to retrieve Organizations
- Updated Data Submission List filters to not use OrganizationListContext, and replace with orgs from listSubmissions API
- Updated Org dropdown to reset to "All" when the selected org is no longer an option
- After a new submission is created, update the orgs, submitter names, and dataCommons lists
- Updated tests to match new implementation
- Fixed lineHeight issue in Data Submission summary section. The collaborators property was taller than all the other properties
- Added a bandage fix for an existing bug. Unsure of cause, but please test to ensure it is fixed for you as well. Added comment …
=> CRDCDH-1738 Data Submission List - Unlock Organization dropdown

src/components/NodeChart/index.test.tsx, src/components/NodeChart/index.tsx
PR to apply truncation to the Individual Pie Chart labels after 14 characters. I tried a few different combinations and 14 characters seems reasonable, but if there's a number that visually looks better, LMK.
<details><summary>New vs. Old</summary>
<p>
</p>
</details> 
- Apply standard truncation when a node label exceeds 14 characters
- Update how we handle label reformatting to try and closer-respect what the MDF dictates
- Add test coverage for label handling
CRDCDH-1976
=> CRDCDH-1976 Fix Node labels overlapping

src/components/StyledFormComponents/StyledLabel.tsx, src/components/StyledFormComponents/StyledSelect.tsx, src/content/operationDashboard/DashboardView.tsx
Minor UX updates to the Operation Dashboard metric dropdown.
- Restyle the Operation Dashboard page to remove negative margins for positioning
- Adjust the dropdown and label styling per UX
- Fix the QuickSight frame not rendering the rounded border
CRDCDH-1428 (Design task)
=> Restyle metric field per UX

src/components/Header/components/HeaderTabletAndMobile.tsx, src/components/Header/components/NavbarDesktop.tsx
This PR fixes an issue where the navbar uses `innerText` to determine which item was clicked – Which works fine until the rendered value is different from the actual value (HTML collapses extra whitespace natively). 
> [!NOTE]
> This is just a bandaid fix, the navigation bar elements should just call the onClick handler with the configuration-based name of the item since we have those details within the context.
- Migrate usage of `innerText` to `textContent`
- Fix mobile navbar crashing when no sublist exists
CRDCDH-1978
=> CRDCDH-1978 Fix: Navbar breaks for names with multiple spaces

src/components/Contexts/CollaboratorsContext.test.tsx, src/components/Contexts/CollaboratorsContext.tsx
This PR addresses an issue where:
1. A completely valid collaborator is added to a submission
2. The collaborator becomes invalid via some action, such as
- Their role changes
- Their org changes
- A study is removed from their org
3. When the submitter goes to the manage collaborators table and changes their permission
4. The Name and Organization fields go blank until saved and reloaded
- If the user does not exist in the potential collaborators, backfill the information from the existing collaborator assignment
- Add an error log for when this occurs – This can be removed if desired
- Update test coverage for this scenario
CRDCDH-2025
=> CRDCDH-2025 Updating an existing collaborator can cause field clearing

src/content/questionnaire/sections/A.tsx
Temporarily removing ORCID input from Submission Request form, will be re-enabled in 3.2.0.
- ORCID input was removed, but the value for the ORCID property sent to the BE remains an empty string.
> [!Note]
> Just noticed we never added ORCID to the Review page. We should add that to the requirements when re-enabling in 3.2.0.
[CRDCDH-2064](https://tracker.nci.nih.gov/browse/CRDCDH-2064) (User Story)
=> CRDCDH-2064 Remove ORCID input from Submission Request form

src/components/Contexts/FormContext.tsx, src/content/questionnaire/sections/A.tsx
Updated `questionnaireData` on API retrieval to be an empty string as well as the ORCID value in the form to be an empty string. This way it will treat ORCID property as unchanged and ignore the field.
N/A
[CRDCDH-2064](https://tracker.nci.nih.gov/browse/CRDCDH-2064) (User Story)
=> CRDCDH-2064 Fix detecting change in ORCID for legacy forms 

src/content/dataSubmissions/DataSubmissionsListView.tsx
This PR addresses two concerns brought up during the 3.1.0 Release Demo; Increase dbGaPID maximum length and rename "node" to "record" for the node count column.
N/A
CRDCDH-2074 (Task)
CRDCDH-2070 (Story)
=> CRDCDH-2074 Rename Node to Record and Incr. dbGaPID length

src/components/Contexts/CollaboratorsContext.test.tsx, src/components/Contexts/CollaboratorsContext.tsx
When an invalid collaborator is removed, it shouldn't allow the user to re-add them. Therefore, the maxCollaborators logic was updated to take this into account to prevent showing an empty dropdown.
- Kept track of all 'unavailable' or invalid collaborators
- Used that as well as the ones currently displaying as a row. Once the invalid collaborator row is removed, it will lower the maxCollaborators count as well to prevent adding that row back
[CRDCDH-2067](https://tracker.nci.nih.gov/browse/CRDCDH-2067) (Bug)
=> CRDCDH-2067 Prevent invalid collaborators from being re-added

src/components/Questionnaire/CustomAutocomplete.tsx
This PR restores the disabled background color on the Cancer Types autocomplete. I think this issue was introduced in #499, but I'm not 100% sure. 
N/A
CRDCDH-2083 (Bug)
=> CRDCDH-2083 Fix Cancer Types Half-Filled Input

src/components/DataSubmissions/CreateDataSubmissionDialog.test.tsx, src/components/DataSubmissions/CreateDataSubmissionDialog.tsx, src/components/DataSubmissions/RadioInput.tsx, src/graphql/createSubmission.ts
This PR extends the "conditionally approved study" functionality by restricting Data Submission creation for a controlledAccess study that has no dbGaPID provided yet. 
> [!Warning]
> This PR marks the Data Submission's "RadioInput" component as deprecated. This component was copied directly from the Questionnaire, and is mostly legacy code. It's only used on the Create a Data Submission dialog, but should not be used going forward.
- Autofill dbGaPID field for controlled access studies, and mark it as readOnly (always)
- If no dbGaPID is populated, show an error next to the dbGaPID field with a tooltip
- Cleanup unused code from RadioInput and fine-tune it for the creation dialog use-case
- Cleanup unnecessary component nesting in the creation dialog
- Refactor the "createSubmission" …
=> CRDCDH-1988 Data Submissions - Conditionally Approved Studies (2/2)

src/components/Contexts/CollaboratorsContext.test.tsx, src/components/Contexts/CollaboratorsContext.tsx, src/components/Questionnaire/CustomAutocomplete.tsx, src/content/dataSubmissions/DataSubmissionsListView.tsx
=> Sync 3.2.0 with 3.1.0

src/components/DataSubmissions/CreateDataSubmissionDialog.tsx
This PR attempts to resolve the ability for users to create >1 Data Submissions by rapidly clicking the Create button or pressing enter multiple times quickly.
React hook form already has functionality to prevent multiple concurrent form submissions, but it requires that the submit handler be async. 
> [!NOTE] 
> This change probably shouldn't be merged directly into 3.2.0, since I made some changes to the dialog there, I don't think this is forward-compatible.
N/A
CRDCDH-2115
=> CRDCDH-2115 Fix Multiple Submit of Create Submission Form

src/components/PansBanner/index.test.tsx, src/components/PansBanner/index.tsx, src/components/Questionnaire/FormContainer.tsx, src/content/questionnaire/sections/A.tsx
This PR adds a OMB banner to the Submission Request page, before the first question.
> [!NOTE]
> There is some slight styling differences between the implementation and design. In particular, the page banner background cuts off much higher up, rather than fading out. Since it's not directly related to this change, I left it untouched. 
>
> I also noticed that the sidebar (ProgressBar) no longer follows the top of the screen when scrolling, even though the styling for it has it set to `position: sticky`. Unsure if this is expected or when it broke, but I left it untouched.
> [!NOTE]
> I wanted to limit the changes since we're close to the 3.1.0 release, but in the future, I think we should migrate the FormContainer "Return to All Submissions" to a prefixElement instead (defined within the …
=> CRDCDH-2086 Add OMB/PANS banner

src/components/DataSubmissions/CreateDataSubmissionDialog.test.tsx, src/components/DataSubmissions/CreateDataSubmissionDialog.tsx, src/config/AuthRoles.ts, src/hooks/useProfileFields.test.ts, src/hooks/useProfileFields.ts
This PR is preparation for Data Submission PBAC controls. Instead of explicitly utilizing the account's assigned studies, we now determine if the Create a Data Submission dialog should utilize the AuthCtx studies or the full list. 
- Cleanup unused mock queries for list orgs in the Create a DS dialog tests
- Define `RequiresStudiesAssigned` variable, which defines the roles that enforce a study selection
- Update Create a DS dialog to utilize the listApprovedStudies instead of their assigned studies based on:
- Is the dialog even open?
- Does the user role require studies be assigned? If not, we call the API
- Does the account have the "All" study assigned? If yes, we call the API
CRDCDH-2113 (Task)
CRDCDH-2023 (US 1 of 2)
CRDCDH-1886 (US 2 of 2)
=> CRDCDH-2113 Create a Data Submission – PBAC Studies Support

src/components/DataSubmissions/DataSubmissionSummary.test.tsx, src/components/DataSubmissions/DataSubmissionSummary.tsx, src/content/organizations/OrganizationView.tsx
This PR is a minor update to the Organization rebranding by enforcing the same field lengths and character restrictions.
> [!NOTE]
> There are more changes in the user story, but they're completely different than original requirements. I'll create a separate task and ticket to track them.
Data Submission Dashboard
- Replace "Organization" column with "Program"
Edit Program
- Remove `size='small'` prop on Edit Org fields (it doesn't seem to change anything)
- Apply the following for Abbreviation:
- Max 100 chars
- Alphanumeric (incl. dash and spaces)
- Placeholder from SR
- Apply the following for Description:
- Max 500 chars
- Placeholder from SR
- Multi-line with resize handle
CRDCDH-1991
CRDCDH-1900
=> CRDCDH-1991 (V2) Additional Organization Rebranding Changes

src/content/users/ProfileView.tsx, src/hooks/useProfileFields.ts
This PR adds the "All" studies option for Federal Leads on the Edit User tool.
> [!Warning]
> When switching roles from anything (e.g. `Submitter`) to `Federal Lead`, MUI throws a warning because the "All" option is programmatically selected, but not available in the study options during the first render. The only solution I could find that worked is [not very clean](https://github.com/CBIIT/crdc-datahub-ui/pull/566/commits/f6e0da767afaddc2178114a8545b510b2ddcb373). I'm open to any alternatives.
- Add `All` option to the Studies list for Federal Leads, selected by default
- Migrate `VisibleFieldState` out of ProfileView into the useProfileFields hook
CRDCDH-2123 (Task)
=> CRDCDH-2123 Support "All" studies for Federal Leads

src/components/DataSubmissions/DataSubmissionListFilters.test.tsx, src/components/DataSubmissions/DataSubmissionListFilters.tsx, src/components/DataSubmissions/DataSubmissionSummary.test.tsx, src/components/DataSubmissions/DataSubmissionSummary.tsx, src/content/dataSubmissions/DataSubmissionsListView.tsx, src/content/organizations/OrganizationView.tsx, src/graphql/listSubmissions.ts
Additional changes for the Program rebranding.
> [!NOTE]
> For testing, the Data Submission `8dea1607-fac8-44d5-a44e-976444fe840a` (No Program DS) was manually updated to remove the Org name and _id.
- Revert the removal of the Organization filter and column on the Data Submission List page and rename it to Program
- Fallback to "NA" when the Program is not assigned on the DS List column and DS Overview
- Add error logging when an error occurs fetching the list of Data Submissions
- Change the Program Name field to be consistently called "Program"
- Previous requirements said to call it "Name" when adding, but "Program" (Organization) when editing
CRDCDH-2139 (Task)
CRDCDH-1900 (US)
=> CRDCDH-2139 Additional Program Rebranding Changes

src/config/AuthPermissions.test.ts, src/config/AuthPermissions.ts, src/content/questionnaire/FormView.tsx, src/hooks/useFormMode.ts, src/utils/formModeUtils.test.ts, src/utils/formModeUtils.ts
Update to support PBAC for Submission Request list view as well as the form. 
- Fixed the Submit button logic as the US mentions that Submission Request form owners are associated with the "create" permission, but aren't actually granted it. Therefore, logic has been updated to support having either the permission or being the form owner
- Verified changes in parent branch (no code changes required) for:
- "Start a Submission Request" button only visible if user has "create" permissions
- "Resume" button only visible if user has "create" permissions and submission is in "New", "In Progress", or "Inquired" status. (Otherwise "View")
- "Review" button only visible if user has "review" permissions and submission is in "Submitted" or "In Review" status. (Otherwise "View")
- The review related …
=> CRDCDH-2099 PBAC - Display Submission Request Action buttons based on permissions

src/content/OperationDashboard/DashboardView.tsx, src/utils/dashboardUtils.test.ts, src/utils/dashboardUtils.ts, src/utils/index.ts
Cleaned up Operation Dashboard logic for content parameters. Also, skipped adding studies parameter when user has "All" study, so that it shows all studies. 
- Separated some of the logic for adding content params to the dashboard to utility functions with tests
- Skipped adding studies parameter when user has "All" study assigned
[CRDCDH-2118](https://tracker.nci.nih.gov/browse/CRDCDH-2118) (Task)
[CRDCDH-2155](https://tracker.nci.nih.gov/browse/CRDCDH-2155) (US 1)
[CRDCDH-1886](https://tracker.nci.nih.gov/browse/CRDCDH-1886) (US 2)
[CRDCDH-1887](https://tracker.nci.nih.gov/browse/CRDCDH-1887) (US 3)
=> CRDCDH-2118 Operation Dashboard – Studies filter utilizes "All" studies selected

src/client.ts, src/components/PermissionPanel/index.test.tsx, src/components/PermissionPanel/index.tsx, src/content/users/ProfileView.tsx, src/graphql/editUser.ts, src/graphql/getMyUser.ts, src/graphql/getUser.ts, src/graphql/index.ts, src/graphql/retrievePBACDefaults.ts, src/hooks/useProfileFields.test.ts, src/hooks/useProfileFields.ts, src/types/Auth.d.ts, src/types/PBAC.d.ts, src/utils/profileUtils.test.ts, src/utils/profileUtils.ts
This PR introduces the ability to configure individual PBAC permissions for an account.
> [!Warning]
> Some known issues / expected things from the backend implementation:
> - You can adjust a Submitter or User's permissions, but no changes will actually be saved. This is expected, but BE should be locking all permissions, and they currently aren't
> - The backend seems to reject some permissions and/or notification selections and returns an error for it. Just uncheck them in the FE for now
> - The visual permission names don't really match the user stories anymore (they keep getting changed)
> - The order of actual permissions in the nested groups may not match the user stories (see below)
> [!NOTE]
> The frontend sorts the groups based on the User Story, but we don't sort the nested …
=> CRDCDH-2105 PBAC – Individual Permissions Control of User Accounts

src/hooks/useProfileFields.test.ts, src/hooks/useProfileFields.ts
This PR updates the `useProfileFields` hook to utilize PBAC instead of RBAC when determining which fields are unlocked, disabled, etc.
> [!NOTE]
> I can't really check this change since the backend won't return data for non-Admins ATM.
N/A
CRDCDH-2102 (FE Task)
=> CRDCDH-2102 fix: The `useProfileFields` hook should utilize PBAC

src/components/Contexts/SubmissionContext.test.tsx, src/components/Contexts/SubmissionContext.tsx, src/components/DataSubmissions/ExportValidationButton.test.tsx, src/config/SubmitButtonConfig.ts, src/content/dataSubmissions/DataSubmission.tsx, src/graphql/submissionQCResults.ts, src/utils/dataSubmissionUtils.test.ts, src/utils/dataSubmissionUtils.ts
The BE moved the Orphaned Files error from `Submission.fileErrors` to within the QC Results API. Updated submit button config to accept QC Results as a param when checking logic to avoid submitting and admin submit when there's orphaned files.
- Added calling QC Results API in parallel to getSubmission API within SubmissionContext, including while polling
- Added the QC Results to the Submit button config to use for determining whether or not to enable the Submit button
- Updated the Orphaned Files logic to use QC Results instead of `Submission.fileErrors`
[CRDCDH-1674](https://tracker.nci.nih.gov/browse/CRDCDH-1674) (Bug)
=> CRDCDH-1674 Fix Orphaned Files error being moved from submission to QC Results

src/components/DataSubmissions/DeleteNodeDataButton.test.tsx, src/components/DataSubmissions/DeleteNodeDataButton.tsx
This PR updates the Delete Node Data button (Data View) to disable it in certain submission states. Per KC:
- Submitted
- Released
- Completed
- Canceled
- Deleted (I added this)
> [!NOTE]
> This bug also needs to go to the backend team so they can update the API.
N/A
CRDCDH-2138
=> CRDCDH-2138 Disable "Delete Node Data" button after submit

src/content/dataSubmissions/DataSubmissionsListView.tsx
This is a minor fix for the generic error `"An error occurred while loading the data."` that appears when creating data submissions using a study that isn't associated with any organization (program).
It can't be replicated all the time, but it seems to do it with the study `1901-2`
- Add null-safe chaining when sorting the Program List for the dropdown filter
- Add the logging util to the try-catch
N/A
=> HOTFIX: Create a Data Submission List View Error

src/components/Questionnaire/LabelCheckbox.tsx, src/components/Questionnaire/ReviewDataListing.tsx, src/components/Questionnaire/ReviewSection.tsx, src/content/questionnaire/sections/C.tsx
PR to fix 508 regression issues with the Submission Request form.
- Use `aria-label` for `LabelCheckbox` instead of `aria-labelledby` 
- Use the correct heading levels for the Review Page (H2 -> H3 -> H4 instead of H2 -> H6 -> H5)
CRDCDH-2151
=> CRDCDH-2151 Submission Request 508 Issues

src/content/questionnaire/FormView.tsx
Previously, we prevented unnecessary API calls by comparing the saved SR with the current state of the SR when pressing the save button; In order to support upcoming auto-delete Submission Request functionality changes, we must always dispatch the saveApplication API call when the user requests it. 
> [!NOTE]
> This is based on the PBAC branch to keep merging simple, but it's very unrelated to the PBAC changes.
- Remove `isEqual` comparison on saveApp functionality
CRDCDH-2186 (FE Task)
=> CRDCDH-2186 Allow save without changes

src/components/Header/components/HeaderTabletAndMobile.tsx, src/components/Header/components/NavbarDesktop.tsx
PR to restore the original visibility of the Uploader CLI Tool, which should always be visible and not hidden based on PBAC. Also, moves the CLI Tool to right after User Profile.
N/A
N/A – PBAC Stories
=> fix: CLI Tool should not be bound by `data_submission:create`

src/config/AuthPermissions.test.ts, src/config/AuthPermissions.ts
The Data Submission create permission for 'Federal Lead' and 'Data Commons Personnel' roles were updated to restrict it to only applying to their own Data Submission.
- Updated 'Federal Lead' role Data Submission create permission to only be allowed to apply to their own Data Submissions
- Updated 'Data Commons Personnel' role Data Submission create permission to only be allowed to apply to their own Data Submissions
- Updated all Data Submission permissions to accept "All" study for Federal Leads as a valid study
[CRDCDH-2212](https://tracker.nci.nih.gov/browse/CRDCDH-2212) (Task)
[CRDCDH-2023](https://tracker.nci.nih.gov/browse/CRDCDH-2023) (US 1)
[CRDCDH-1886](https://tracker.nci.nih.gov/browse/CRDCDH-1886) (US 2)
[CRDCDH-1887](https://tracker.nci.nih.gov/browse/CRDCDH-1887) (US 3)
=> CRDCDH-2212 Restrict Data Submission 'create' permission scope for specific roles

src/components/StyledFormComponents/StyledAsterisk.tsx, src/content/users/ProfileView.tsx
PR to update the ProfileView to ensure asterisks are shown near required fields, and HTML5 validation errors are visible.
> [!NOTE]
> The tests are failing due to the base branch, but everything works locally.
- Fix the studies and data commons field missing the HTML5 required attribute
- Update the StyledAsterisk (form components) to forward the ref so we can add additional styling to the component
- Update all ProfileView fields to conditionally render the asterisk if applicable
- Users editing their own profile see FN and LN as required
- Others with User Management permissions see Role/Studies/etc as required
- Remove forwarding of the API error to the snackbar, as it contains very non-user-friendly details
CRDCDH-2184
=> CRDCDH-2184 Fix missing `required` asterisks

src/components/PermissionPanel/index.test.tsx, src/graphql/retrievePBACDefaults.ts, src/types/PBAC.d.ts, src/utils/profileUtils.test.ts, src/utils/profileUtils.ts
This PR fixes an oversight where the order of the PBAC option must be sorted based on an arbitrary order, rather than the order returned by the API.
- Sort the PBACDefaults within each group by the `order` property given
- Update coverage in multiple areas to test this
N/A
=> feat: Sort PBACDefaults within their groups

src/config/AuthRoles.ts
Sort the User Roles array to reflect the order described in the User Story. 
N/A
N/A
=> fix: Sort the order of AuthRoles per the US

src/components/ProgressBar/ProgressBar.test.tsx, src/components/ProgressBar/ProgressBar.tsx
Proposed PR to migrate #585 to Permission Based Access Control.
Some of the scenarios I tested and compared to DEV2:
- Admin with View only
- Federal Lead with Submit permission (also tested Resubmit)
- Submitter with Submit
It seems to be correct, but I'm not 100% that this is the correct migration. This also includes updates to the test coverage so we can pass permissions in the unit tests.
=> Migrate CRDCDH-2199 to PBAC

src/components/Questionnaire/ApproveFormDialog.tsx, src/components/Questionnaire/InquireFormDialog.tsx, src/components/Questionnaire/RejectFormDialog.tsx, src/components/StatusBar/StatusBar.test.tsx, src/components/StatusBar/components/HistorySection.tsx, src/config/QuestionnaireTooltips.ts
PR to add general improvements to the Submission Request page.
> [!NOTE]
> I commented out tests for `Canceled` and `Deleted` statuses due to TypeScript issues, I'll uncomment them in CRDCDH-2187.
- Render tooltips on the status transition in the Submission Request History Dialog
- Add test coverage for SR History Dialog changes (tooltips and also conditional approval didn't have any coverage)
- Increase the height of Review Comments inputs (Approve, Inquire, Reject) and make them resizable
CRDCDH-2188 (FE Task)
CRDCDH-2158 (US)
=> CRDCDH-2188 Submission Request Status Tooltips

src/components/Header/components/HeaderTabletAndMobile.tsx, src/components/Header/components/NavbarDesktop.tsx, src/content/Login/Controller.test.tsx, src/content/Login/Controller.tsx, src/content/index.tsx, src/router.tsx
This PR addresses two primary things:
- Login controller refactoring
- Fix the alignment of the button-based sub-items (logout, cli tool, etc)
<details><summary>Navbar alignment issue</summary>
<p>
BEFORE (QA2): Look at the "g" in Login compared to the horizontal line
AFTER (DEV2): Look at the "g" in Login compared to the horizontal line
USED FOR TESTING (insert inside the root element)
```
<hr style="
position: fixed;
left: 0;
right: 0;
z-index: 9999;
top: 247.1px;
">
```
</p>
</details> 
(UX changes)
- Fix the vertical and horizontal alignment of navbar buttons to match links
(Refactoring changes)
- Rename the `login` content folder to `Login`
- Refactor the login controller code to be cleaner and follow a more logical flow (opinion)
- Return the SuspenseLoader from the LoginController …
=> Refactor Login Flow & Fix Navbar Button Styling

src/components/DataSubmissions/ValidationControls.tsx
Allow users with the "review" permission to validate before and after a Data Submission has been submitted.
N/A
[CRDCDH-2098](https://tracker.nci.nih.gov/browse/CRDCDH-2098) (Task)
[CRDCDH-2023](https://tracker.nci.nih.gov/browse/CRDCDH-2023) (US)
=> CRDCDH-2098 Hotfix: Allow review permission to validate before and after submitted submission

src/components/Collaborators/CollaboratorsDialog.test.tsx, src/components/Collaborators/CollaboratorsDialog.tsx, src/components/DataSubmissions/DataSubmissionSummary.tsx
Restrict the Submitter from modifying the Collaborators within the dialog when a submission is in Completed, Canceled, or Deleted status.
N/A
[CRDCDH-2271](https://tracker.nci.nih.gov/browse/CRDCDH-2271) (Task)
[CRDCDH-2035](https://tracker.nci.nih.gov/browse/CRDCDH-2035) (US)
=> CRDCDH-2271 Limit Collaborator editing for specific Submission statuses

src/components/StatusBar/components/HistorySection.tsx
This PR is a hotfix for the CRDCDH-2156 submission request status descriptions – Trying to hover over each status is very challenging because the tooltip is not disappearing.
<details><summary>Issue</summary>
<p>
https://github.com/user-attachments/assets/e3b60b79-2680-41b9-a0ca-545d854fe012
</p>
</details> 
N/A
CRDCDH-2156
=> CRDCDH-2156 HOTFIX: Tooltip should ignore interactivity

package-lock.json, src/hooks/useBuildReduxStore.ts, src/types/DataCommon.d.ts, src/types/DataModelNavigator.d.ts, src/utils/dataModelUtils.test.ts, src/utils/dataModelUtils.ts
Added support for displaying Release Notes as a tab using markdown.
> [!NOTE]
> It is currently setup to use the latest release notes. This may change, will address in separate PR if necessary.
- Retrieved the latest changelog/release notes assets from the DMN manifest and updated the Redux state to display as a tab in the DMN
- DMN changes in https://github.com/CBIIT/Data-Model-Navigator/pull/155
[CRDCDH-2260](https://tracker.nci.nih.gov/browse/CRDCDH-2260) (Task)
[CRDCDH-2231](https://tracker.nci.nih.gov/browse/CRDCDH-2231) (US)
=> CRDCDH-2260 Model Navigator - Add Release Notes tab

src/content/ModelNavigator/Controller.tsx
This is a hotfix for CRDCDH-2266; If you're on an old version of the Data Model, then click the Navigator link from the navbar, the URL updates, but the UI never rebuilds the latest model version.
N/A
CRDCDH-2266
=> fix: Version changing not rebuilding UI

src/components/DataSubmissions/DataUpload.test.tsx, src/components/DataSubmissions/DataUpload.tsx, src/components/DataSubmissions/MetadataUpload.test.tsx, src/components/DataSubmissions/MetadataUpload.tsx
This PR applies some minor styling changes to the Data Model link and CLI Version displays on the DS Dashboard, per the latest UX design.
> [!NOTE]
> The UX design specifies that these elements should be 10px font size, but when using that size, it's incredibly small and looks very different from the design (IMO). I increased it to 13px, which looks closer to the actual design. 
N/A
CRDCDH-2159 (US 1 – DM Link)
CRDCDH-2274 (US 2 – CLI Vers)
=> Style Model Link & CLI Version Adornments

src/content/organizations/OrganizationView.tsx, src/content/users/ProfileView.tsx
This PR extends the Program study selection box to match the Edit User page.
- Migrate Edit User study box to program page (organization)
- Fix: A very long single selected value may wrap multiple lines instead of just truncate
- Fix: Searching for a short study (e.g. "CMB") causes the result items to fill only half of the full parent width
CRDCDH-1610 (Task)
=> CRDCDH-1610 Program Page – Standardize Study Select

src/components/DataSubmissions/DataUpload.tsx, src/components/DataSubmissions/MetadataUpload.tsx
Adjusted per KC request (smaller font, more gap between version label and the version itself). I left the font color alone since it's still what the design uses. 
LMK if it needs to be adjusted further. 
N/A
N/A
=> Fine-tune Version Adornment Styling

src/components/ErrorDetailsDialog/index.tsx
Fixes an issue where, when the content of the Error details dialog is very tall, the dialog shows a scrollbar inside itself instead of using the page body to scroll. 
This doesn't need to be merged before the demo.
N/A
CRDCDH-2149
=> fix: ErrorDetailsDialog should scroll on page body, not dialog body

src/components/Footer/FooterDesktop.tsx, src/components/Footer/FooterMobile.tsx, src/components/Footer/FooterTablet.tsx
PR to remove z-index from the footer, which causes it to overlap with page content. 
N/A
CRDCDH-2331
=> CRDCDH-2331 Remove `z-index` from footer

src/components/ErrorDetailsDialog/index.tsx
Fix the ErrorDetailsDialog "Close" button not being centered. Unsure when this broke
N/A
N/A
=> fix: Close button not centered

src/components/CancelApplicationButton/index.test.tsx, src/components/CancelApplicationButton/index.tsx
PR to update the verbiage used in the "Restore Submission Request" dialog when restoring DELETED submission requests.
- Change the phrase "[...] previously canceled" to "[...] previously deleted" when restoring a Deleted SR
- Update test coverage for this
CRDCDH-2454
=> CRDCDH-2454 Incorrect verbiage for restoring deleted SRs

conf/nginx.conf, docs/Nginx.md, src/components/ExportRequestButton/pdf/Generate.ts, src/components/ProgressBar/ProgressBar.tsx, src/components/Questionnaire/FormContainer.tsx, src/config/HeaderConfig.ts, src/content/dataSubmissions/DataSubmissionsListView.tsx, src/content/index.tsx, src/content/questionnaire/FormView.tsx, src/content/questionnaire/ListView.test.tsx, src/content/questionnaire/ListView.tsx, src/content/questionnaire/sections/A.tsx, src/router.tsx
This PR renames the Submission Request URL from "/submission[s]" to "/submission-request[s]", and provides a SEO-friendly redirect within our Nginx config.
> [!Warning]
> Some notes about the Nginx redirect:
>
> - The redirect only works when navigating from an external browser action, such as a bookmark or link from another application. Any **outdated** links from within our application will result in a 404 page, but I think I updated every outdated reference.
> - The redirect will forward any query parameters for the list page only (e.g. applied filters). I didn't forward the query params on the individual submission-request URL since I don't think we use them there.
- Rename `/submissions` and `/submission/{_ID}` to `/submission-requests` and `/submission-request/{_ID}`, respectively
- …
=> CRDCDH-2418 Update Submission Requests URL

conf/nginx.conf
This PR changes the production Nginx caching policies to align with a more React-specific deployment. Specifically:
- Enforce NO caching on the index.html file, which references the React chunks
- Enforce 1hr max cache on the injectEnv.js file
- Enforce a 1mo cache duration for most static assets
These are somewhat arbitrary baselines, but we can adjust as needed.
N/A
CRDCDH-2450 (Task)
=> CRDCDH-2450 Add react-specific caching policies

package-lock.json
PR to address an issue where Data Models might (incorrectly) duplicate relationships between nodes, and that duplicate relationship results in the loading template (TSV) containing the column for the parent ID twice.
This is present in the CTDC Data Model for Data File node.
- Upgrade DMN to v1.2.2 https://github.com/CBIIT/Data-Model-Navigator/commit/5b3999470f65b63459888c5c990adad027242a35
CRDCDH-2470 (Bug)
=> CRDCDH-2470 Skip duplicate node relationships in Model Navigator

package-lock.json, package.json
Reorganized the sections within package.json and moved deps between dependencies and devDependencies, to better reflect their purpose.
- Move deps between dependencies and devDependencies and vice versa. Also sorted them
- Moved "scripts" section closer to the top, and less important sections ("overrides", "browserlist") to the bottom
Notes:
- The "overrides" section should remain until we upgrade the TypeScript version. Otherwise if you have a newer global TypeScript version installed then there seems to be some conflicts.
- The "@typescript-eslint/eslint-plugin" can be slightly upgraded, but not enough to get rid of the "unsupported typescript version". This is due to CRA being deprecated and being a blocker. Will need to upgrade when we transition away from CRA.
- The "@axe-core/react" …
=> CRDCDH-2422 Reorganized package.json

.storybook/main.ts, package-lock.json, package.json, src/components/Questionnaire/SwitchInput.stories.tsx, src/components/Questionnaire/SwitchInput.tsx, src/content/questionnaire/sections/D.tsx, src/content/questionnaire/sections/Review.tsx
Updated the styling of the Switch Input used within Submission Request forms.
- Added a gradient background for switch inputs toggled on, with a slight animation
- Updated colors of switch input
- Swapped the order of "Proteomics" and "Imaging", as well as updated the Review section to reflect their placements
- Added SR switch input to storybook
- Added new storybook addon to control pseudo states and specify selectors
[CRDCDH-2420](https://tracker.nci.nih.gov/browse/CRDCDH-2420) (Task)
[CRDCDH-2389](https://tracker.nci.nih.gov/browse/CRDCDH-2389) (US)
=> CRDCDH-2420 Submission Request Switch Input

package-lock.json, src/components/AdminPortal/Organizations/StudyTooltip.tsx, src/components/AdminPortal/Studies/ApprovedStudyFilters.tsx, src/components/Carousel/index.tsx, src/components/DataSubmissions/ValidationStatistics.stories.tsx, src/components/NodeChart/index.tsx, src/components/TruncatedText/index.test.tsx, src/components/TruncatedText/index.tsx, src/content/ModelNavigator/NavigatorView.stories.tsx, src/content/questionnaire/ListFilters.tsx
This PR addresses 508 accessibility regressions and/or new issues introduced over the span of 3.2.0 development.
> [!NOTE]
> Details on the Data Submission Statistics 508 issue:
> The carousel is (correctly) marking the containers that aren't visible as `aria-hidden`, but the nested charts have `tabindex` attributes on them, which causes a accessibility issue.
>
> The only working solution I could find for the 508 issues on the carousel was to override the tabIndex attributes on the pie chart elements by manipulating the DOM directly. Recharts does not seem to provide a way to pass props to the SVG's `<g>` element, which are the ones with the tabindex.
- Fix the following 508 issues in the core frontend app
- Incorrect htmlFor attribute on accessType filter
- `other X` studies color …
=> CRDCDH-2502 508 Accessibility Regressions

src/content/dataSubmissions/DataSubmissionsListView.tsx
The sorting for the "dataFileSize" field was sorting by string instead of the numerical size. Updated to use the number of bytes instead of sorting by string. 
N/A
[CRDCDH-2415](https://tracker.nci.nih.gov/browse/CRDCDH-2415)
=> CRDCDH-2415 Fix Data File Size sorting by size instead of string

src/components/InstitutionListFilters/index.tsx
While doing final check I noticed I was unable to switch pages on the Institution List table. This was due to the useEffect deps, so they were changed to match other filters.
N/A
[CRDCDH-2472](https://tracker.nci.nih.gov/browse/CRDCDH-2472)
=> CRDCDH-2472 Hotfix: Fix issue causing institution list table from switching pages

src/components/GenericTable/ColumnVisibilityPopper.test.tsx, src/components/GenericTable/ColumnVisibilityPopper.tsx, src/hooks/useColumnVisibility.ts
Previously, the "RESET" button in the column visibility popper just set all columns to visible. This was updated to instead reset to default.
- Fixed "RESET" button in the column visibility popper to reset to default based on columns that are hidden by default
- Fixed issue where deleting local storage value for column visibility caused site to crash
[CRDCDH-2651](https://tracker.nci.nih.gov/browse/CRDCDH-2651)
=> CRDCDH-2651 Bug: Fix reset button in column visibility popper

src/components/InstitutionListFilters/index.tsx, src/content/Institutions/ListView.tsx
Found additional issues while testing. Fixed issue where you select a page other than 1 and reload, but the page would not persist. Also, fixed issue where there was a lot of extra changes being made to search params with the same values, causing weird URL flicker.
N/A
[CRDCDH-2472](https://tracker.nci.nih.gov/browse/CRDCDH-2472)
=> CRDCDH-2472 Hotfix: Fix table page not persisting after page reload

src/components/ProgressBar/ProgressBar.tsx, src/content/questionnaire/FormView.tsx, src/layouts/index.tsx
PR to simulate native browser functionality by moving the scroll position to the top of the page on navigate. The only exception is the Submission Request form, where the page should navigate to the top of the form (already implemented)
N/A
CRDCDH-2624 (Task)
CRDCDH-2608 (US)
=> CRDCDH-2624 Reset scroll position on navigate

src/content/users/ListView.tsx, src/content/users/ProfileView.tsx, src/hooks/useProfileFields.test.ts, src/hooks/useProfileFields.ts
Update to allow Federal Leads to modify other Federal Lead users, except for their role.
> [!NOTE]
> The BE will handle filtering out Federal Lead users from the listUsers API. Currently, they are being filtered on the FE since pagination/sorting/filtering is on the FE, but the API is still returning all users of all roles.
- In the Manage Users list page, it was updated so that the Federal Lead role is selected by default as a filter, and disable the select, since there is no other options available
- Updated searchParams to use the Federal Lead role as the default when user is a Federal Lead
- Unlocked all fields within the Profile View while editing another Federal Lead user, except for the role field
- Updated select inputs to use the styled components instead …
=> CRDCDH-2595 Allow Federal Lead role to manage the Federal Lead users

src/components/ExportRequestButton/index.stories.tsx, src/components/Questionnaire/ReviewFileTypeTable.tsx
This PR is an attempted fix for the content overlapping happening in the table of the Submission Request PDF export. I'm not really sure if this will fix it 100%, but increasing the row height seemed to solve the issue.
- Bump the row height of the Review page table 
- Add a very basic storybook for the export PDF button
CRDCDH-2530
=> CRDCDH-2530 Fix Overlapping in PDF Table export

src/components/NodeChart/index.tsx
PR to fix the alignment of the node chart statistics label. Since the element is no longer a block, we need to use text align instead.
https://www.chromatic.com/test?appId=67cb4ee7b4e3bf6f42f5a7c5&id=681e2362173f1a199aca29ce
N/A
N/A
=> fix: Broken alignment of statistic label

src/components/DataSubmissions/DataSubmissionSummary.test.tsx, src/components/DataSubmissions/DataSubmissionSummary.tsx, src/content/dataSubmissions/DataSubmissionsListView.tsx, src/content/organizations/ListView.tsx, src/content/organizations/OrganizationView.tsx, src/content/studies/ListView.tsx, src/content/studies/StudyView.tsx, src/content/users/ProfileView.tsx, src/types/ApprovedStudies.d.ts
This PR renames the term Primary Contact to Data Concierge anywhere pertaining to Data Submissions, with the only exception being the Submission Request pages. 
Internally we still just use Primary Contact (e.g. queries)
N/A 
CRDCDH-2701
CRDCDH-2635
=> CRDCDH-2701 Rename "Primary Contact" to "Data Concierge"

src/components/ModelSelection/FormDialog.test.tsx, src/components/ModelSelection/FormDialog.tsx, src/components/ModelSelection/index.test.tsx, src/components/ModelSelection/index.tsx
When the model version is updated, the validation statuses are reset. This is in-sync with the BE, without having to retrieve the entire submission again.
- Set both metadata and data file validation statuses to "New"
- Updated warning dialog message
[CRDCDH-2695](https://tracker.nci.nih.gov/browse/CRDCDH-2695) (Task)
[CRDCDH-2632](https://tracker.nci.nih.gov/browse/CRDCDH-2632) (US)
=> CRDCDH-2695 Reset validation statuses when model version is changed

src/content/dataSubmissions/DataActivity.tsx
Created a mapping for the existing styling of the batch statuses, and added styling for the "Uploading" status.
N/A
[CRDCDH-2697](https://tracker.nci.nih.gov/browse/CRDCDH-2697) (Task)
[CRDCDH-2612](https://tracker.nci.nih.gov/browse/CRDCDH-2612) (US)
[CRDCDH-2696](https://tracker.nci.nih.gov/browse/CRDCDH-2696) (UX)
=> CRDCDH-2697 Update batch status styling based on status value

src/components/AccessRequest/FormDialog.test.tsx, src/components/AccessRequest/FormDialog.tsx, src/components/DataSubmissions/CreateDataSubmissionDialog.stories.tsx, src/components/DataSubmissions/CreateDataSubmissionDialog.test.tsx, src/components/DataSubmissions/CreateDataSubmissionDialog.tsx
This PR extends the standardization of study name formatting by also using the standard format on:
- The Create a Data Submission dialog
- The Request Access dialog
- Implement formatFullStudyName on Request Access / Create a DS dialogs
- Update test coverage as required
- Add storybook for Create a Data Submission dialog (just basic scenarios)
- Disabled another Access Request test failing in CI ([example](https://github.com/CBIIT/crdc-datahub-ui/actions/runs/15114960995/job/42483192604?pr=717))
CRDCDH-2743 (Task)
CRDCDH-2742 (US)
=> CRDCDH-2743 Standardize Study Display

docs/Data_Submissions.mdx, src/config/DashboardTooltips.ts, src/config/SubmitButtonConfig.ts, src/content/dataSubmissions/DataSubmission.tsx, src/content/dataSubmissions/DataSubmissionActions.stories.tsx, src/content/dataSubmissions/DataSubmissionActions.tsx, src/utils/dataSubmissionUtils.test.ts, src/utils/dataSubmissionUtils.ts
Added Storybook support for all of the Data Submission submit button reasons for being disabled. Also, updated the button to show regular submit when user has admin submit permission.
- Added storybook support for all scenarios regarding the DS Submit button, including disabled conditions, admin submit conditions, and admin performing regular submit
- Added basic storybook support for all additional DS action buttons
- Reordered submit button conditions in terms of criticality, so that the most critical conditions show their tooltip first
- Updated documentation slightly to include regular submit scenario and added a note about order
- Updated DataSubmissionActions to prefer using submission context instead of prop drilling
- Moved check for uploading batch to within the submit button …
=> CRDCDH-2698 Submit button improvements

src/content/organizations/OrganizationView.tsx, src/utils/index.ts, src/utils/studyUtils.test.ts, src/utils/studyUtils.ts
Within the Edit Program page, when a study is assigned to multiple programs, a warning dialog will show.
> [!NOTE]
> ~There is a BE error that shows up when assigning a study to a program when the study belongs to the "NA" program.~ Edit: It was fixed. 
- Added warning dialog when a study is being assigned to multiple programs
- Added utility function to check for multiple programs with tests
[CRDCDH-2763](https://tracker.nci.nih.gov/browse/CRDCDH-2763) (Task)
[CRDCDH-2585](https://tracker.nci.nih.gov/browse/CRDCDH-2585) (US)
=> CRDCDH-2763 Add warning when assigning study to multiple programs

src/content/dataSubmissions/DataActivity.tsx
Increased font weight for an 'Uploading' Batch.
[CRDCDH-2697](https://tracker.nci.nih.gov/browse/CRDCDH-2697) (Task)
[CRDCDH-2612](https://tracker.nci.nih.gov/browse/CRDCDH-2612) (US)
=> CRDCDH-2697 Update 'Uploading' font weight

src/components/ModelSelection/index.tsx
When the validation status is reset after a model version change, the stats still remain as they were before. This can be misleading. Therefore, I updated all of the stats to "New" after the model version change.
N/A
[CRDCDH-2695](https://tracker.nci.nih.gov/browse/CRDCDH-2695)
=> CRDCDH-2695 Update stats to "new" when model version changes

src/components/StatusBar/components/HistorySection.tsx, src/components/SummaryList/TooltipList.stories.tsx, src/components/SummaryList/TooltipList.test.tsx, src/components/SummaryList/TooltipList.tsx, src/components/SummaryList/index.tsx, src/content/questionnaire/ListView.tsx
Display pending conditions in a bullet list within the tooltip.
- Created reusable `TooltipList` to list out items in a bullet list
- Updated History dialog alert tooltip and SR List status alert tooltip to use `TooltipList`
- Added storybook and test support
[CRDCDH-2899](https://tracker.nci.nih.gov/browse/CRDCDH-2899) (Task)
[CRDCDH-2860](https://tracker.nci.nih.gov/browse/CRDCDH-2860) (US)
=> CRDCDH-2899 Display pending conditions in a bullet list within tooltip

src/components/DataSubmissions/ValidationStatistics.stories.tsx
The validation statistics were updated to use submission context, but the storybook was not updated with the provider. Issue was introduced in https://github.com/CBIIT/crdc-datahub-ui/pull/747. 
- Added the submission context provider to the validation statistics storybook
- Added control for submission context status
- Kept everything else the same. The "default" option looks weird on full-screen, but likely just a container issue, not a component issue. Out of scope for now, will address in future.
[CRDCDH-2831](https://tracker.nci.nih.gov/browse/CRDCDH-2831) (Task)
[CRDCDH-2767](https://tracker.nci.nih.gov/browse/CRDCDH-2767) (US)
=> CRDCDH-2831 Bug: Fix broken storybook stats

src/components/DataSubmissions/CreateDataSubmissionDialog.stories.tsx, src/components/DataSubmissions/CreateDataSubmissionDialog.test.tsx, src/components/DataSubmissions/CreateDataSubmissionDialog.tsx, src/graphql/getMyUser.ts
Prevent a user from creating a Data Submission when they select a study that is pending a model change.
- Updated Create a DS dialog to disable "Create" button when the study selected has `pendingModelChange` set to true. Also, included a tooltip for justification as to why the button is disabled
- Updated getMyUser query to include `pendingModelChange` property (listApprovedStudies already includes it)
- Added storybook support for pending changes scenario, as well as a test 
[CRDCDH-2901](https://tracker.nci.nih.gov/browse/CRDCDH-2901) (Task)
[CRDCDH-2886](https://tracker.nci.nih.gov/browse/CRDCDH-2886) (US)
=> CRDCDH-2886 Conditional Approval - Data Submission Creation

CHANGELOG.md, src/components/PageBanner/index.stories.tsx, src/content/dataSubmissions/DataSubmission.tsx, src/content/dataSubmissions/DataSubmissionsListView.tsx, src/content/questionnaire/ListView.test.tsx, src/content/questionnaire/ListView.tsx
Renamed the "Data Submission(s) List" page to "Data Submissions". Also, renamed "Submission Request(s) List" to "Data Submissions". Updated across all found instances.
N/A
[CRDCDH-2904](https://tracker.nci.nih.gov/browse/CRDCDH-2904) (Task)
[CRDCDH-2861](https://tracker.nci.nih.gov/browse/CRDCDH-2861) (US)
=> CRDCDH-2904 Renaming Data Submission List and Submission Request List page titles

src/components/AccessRequest/index.stories.tsx
Chromatic caught a failing storybook test involving a tooltip. Updated to make storybook test pass.
N/A
[CRDCDH-2905](https://tracker.nci.nih.gov/browse/CRDCDH-2905) (Task)
[CRDCDH-2846](https://tracker.nci.nih.gov/browse/CRDCDH-2846) (US)
=> CRDCDH-2905 Fix failing storybook test

src/components/DataSubmissions/ValidationStatus.test.tsx, src/components/DataSubmissions/ValidationStatus.tsx
Logic previously expected `validationType` to be null as a default value, but now it is an empty array (Due to BE Prisma change). This caused the validation status to show as In-Progress, when it shouldn't be shown. Updated to check array length instead.
N/A
N/A
=> Bug: Fix validation type default value causing Validation status to show In-Progress

src/components/GenericTable/index.tsx, src/content/users/ListView.test.tsx, src/content/users/ListView.tsx, src/test-utils/factories/auth/AuthCtxStateFactory.ts, src/utils/profileUtils.test.ts, src/utils/profileUtils.ts, tsconfig.json
Added a "User" filter within the Manage Users list page.
- Added new filter "User" within Manage Users list page to filter by:
- `firstName`
- `lastName`
- `email`
- `lastname, firstName` (How "name" appears on the table)
- `firstName lastName`
- `lastName firstName`
- Only apply search when "User" filter has more than 3 characters typed in
- Added user filter to search params
- Updated default message when table yields no results
- Added test coverage
[CRDCDH-2993](https://tracker.nci.nih.gov/browse/CRDCDH-2993) (Task)
[CRDCDH-2965](https://tracker.nci.nih.gov/browse/CRDCDH-2965) (US)
=> CRDCDH-2993 Add 'User' filter to Manage Users list page

src/components/Questionnaire/AutocompleteInput.tsx, src/content/users/ProfileView.test.tsx, src/content/users/ProfileView.tsx
Within the "Edit User" page, the Institution select dropdown was replaced with an autocomplete input.
- Replaced Institution select dropdown with an autocomplete input
- Added basic test coverage for institutions autocomplete
[CRDCDH-3016](https://tracker.nci.nih.gov/browse/CRDCDH-3016) (Task)
[CRDCDH-3014](https://tracker.nci.nih.gov/browse/CRDCDH-3014) (US)
=> CRDCDH-3016 Replace Institution select with an autocomplete input

src/components/DataSubmissions/DataSubmissionSummary.test.tsx, src/components/DataSubmissions/DataSubmissionSummary.tsx, src/components/HistoryDialog/index.tsx, src/content/dataSubmissions/DataSubmissionActions.stories.tsx, src/content/dataSubmissions/DataSubmissionActions.test.tsx, src/content/dataSubmissions/DataSubmissionActions.tsx, src/content/dataSubmissions/DataSubmissionsListView.tsx, src/graphql/listSubmissions.ts
Updated Release button labeling and added tooltips to Release statuses to include which data commons the submission was released to. 
- Updated the "Release" button label in the Data Submission dashboard to "Release to [DC]"
- Within the Data Submission list table, when the status is anything, but has had a History event indicating the submission has been Released in the past, there will be a tooltip with "Released to [DC]"
- Within the Data Submission full history dialog, when hovering over the "Released" status, it will show a tooltip with "Released to [DC]"
- Added test coverage for the updated label and tooltips
[CRDCDH-2994](https://tracker.nci.nih.gov/browse/CRDCDH-2994) (Task)
[CRDCDH-2848](https://tracker.nci.nih.gov/browse/CRDCDH-2848) (US)
=> CRDCDH-2994 Update Data Submissions Release Labelling

src/content/dataSubmissions/DataSubmissionsListView.tsx
Previous US said to display the "Released to <DC>" for any status. It has since been updated to only show when status is "Released" within the Data Submissions list page.
N/A
[CRDCDH-2994](https://tracker.nci.nih.gov/browse/CRDCDH-2994) (Task)
[CRDCDH-2848](https://tracker.nci.nih.gov/browse/CRDCDH-2848) (US)
=> CRDCDH-2994 Update 'Released to <DC>' tooltip to only show when status is Released

src/content/questionnaire/FormView.tsx
Adds a contextual tooltip to the “Next” button on the final page of the Submission Request questionnaire. When the button is disabled, the tooltip displays "Click ‘Save’ to validate your answers. Once all pages are complete, you can proceed to the Review page to submit".
- Added tooltip to the final page's Next button (shows when required fields are incomplete or the page was not saved)
- Used StyledFormTooltip from StyledFormComponents, as well as the customizations from the cancel button, so that the visuals match
CRDCDH-3100
=> CRDCDH-3100 Tooltip on disabled final “Next” in Submission Request

src/components/AccessRequest/index.stories.tsx, src/components/DataSubmissions/CreateDataSubmissionDialog.stories.tsx, src/components/DataSubmissions/CreateDataSubmissionDialog.test.tsx, src/components/DataSubmissions/CreateDataSubmissionDialog.tsx, src/graphql/listApprovedStudies.ts, src/test-utils/factories/approved-study/ApprovedStudyFactory.ts, src/types/ApprovedStudies.d.ts
Within the Create a Data Submission dialog, updated the tooltip for the disable "Create" button to include a message for pending GPA. Also, updated it to display multiple conditions in the same tooltip, if they exist.
- Added `isPendingGPA` to Approved Study, factory, and within listApprovedStudies API
- Updated disabled "Create" button tooltip to include new pending GPA message and support displaying multiple at once
- Added test coverage and storybook stories for the new tooltips
- Updated tests/storybook that were missing factory
[CRDCDH-3128](https://tracker.nci.nih.gov/browse/CRDCDH-3128)
=> CRDCDH-3116 Prevent creation of Data Submission when pending GPA

src/config/AuthPermissions.ts, src/config/AuthRoles.ts, src/hooks/useProfileFields.test.ts, src/hooks/useProfileFields.ts
This PR hides the PBAC panel from external users on their profile page only. If they happen to get Manage Users access, they would still see it under manage users.
- Repurpose a config for external users array
- Update Profile Fields hook to reflect new requirements (hide PBAC from profile page)
CRDCDH-3112 (US)
CRDCDH-3114 (Task)
=> CRDCDH-3114 External users should not see their PBAC panel

.github/workflows/test.yml
Coveralls.io instability causing our Unit Testing action to fail. This will just ignore coveralls errors.
=> fix: Coveralls.io issues causing test job to fail

src/components/GenericTable/ColumnVisibilityPopper.tsx
PR to fix the hidden border on the Column Visibility toggle for grouped columns.
> [!NOTE]
> I'm not sure why there was a negative margin, but the spacing seems to be correct with it removed (15px below the last toggle, and 15px above the group title).
N/A
CRDCDH-3251 (Bug)
=> CRDCDH-3251 Fix Column groups missing border

src/content/studies/StudyView.tsx
PR to fix an oversight where dbGaP ID and GPA Name should not be required fields, even when the study is controlled access.
> [!NOTE]
> The backend has to update the restrictions for dbGaP ID too, so saving will still show an error.
N/A
CRDCDH-3288 (Task)
CRDCDH-3287 (US)
=> CRDCDH-3288 dbGaPID and GPA should be optional fields
